swagger-api/swagger-js

.gitignore
README.md
gulpfile.js
package.json

This pull-request add gulp as a build tool (should address #181).
It's a start, but to be ideal, I think the following is needed:

[develop 2.0] Use Gulp as build tool

---

README.md
lib/swagger.js

Turn the existing authorization to be a default and allow an override to be passed in for each api client that is created.
This resolves #109.

Allow multiple APIs to be accessed at once

---

lib/swagger.js

When a user does not pass in the opts argument the code will shift the arguments so that the callbacks still get set correctly.  There is a bug that cuases the error callback to be set to null if opts is not passed in.  This fixes swagger-api/swagger-js#203.

Set arg4 to callback when no opt passed in

---

src/js/swagger.js
src/js/swaggerHttp.js

This PR fix useJQuery parameter broken (SwaggerJS try to use Shred sometimes even if useJQuery is specified).
The ``useJquery`` parameter wasn't given to operations and SwaggerHTTP wasn't able to find it (always undefined) in execute (https://github.com/swagger-api/swagger-js/blob/develop_2.0/src/js/swagger.js#L673)

Fix jQuery HTTP

---

src/js/swagger-compat.js

Expanding on issue #121.
This supports regular expressions in path parameters.
For example: `@Path( "/{first : (?i)[\\w]{2}[\\d]{2}}5/{second : (?i)[\\d]{4}}" )`
will allow calls to `basepath/ab125/1234`
but will reject calls to `basepath/abcd5/1234`, `basepath/ab12/1234`, `basepath/ab125/12345`, or others that don't fit the regex pattern.

regex pattern matching fix

---

src/js/swaggerHttp.js

Hi there,
Currently, there is no way to obtain the statusText from the response in the response handlers. In our case, we have a need for this as we have meaningful statusText that we need to act upon. This pull request adds response.statusText to the response out object to expose meaningful statusText.
I refrained from generating the lib/swagger-client.js and lib/swagger-client.min.js files. If you could forward-port it to the master branch, this would be great.
Let me know if there is anything additional I can do!
Thanks for your hard work and great library!

Expose response.statusText in the response out object

---

README.md
gulpfile.js

* Resurrected the `coverage` task
* `test` task no longer runs against instrumented code so that failures
in the core libraries are easier to diagnose
* The default Gulp task now builds the browser binaries to avoid commits
without updated binaries

Update Gulp flow and README to reflect

---

lib/client.js

`responseObj` variable was meant to be used here

Pass responseObj to converter

---

package.json

Currently, `require('swagger-client')` doesn't work, because the npm package won't include the index.js file. This PR fixes that.

add index.js to package.json files

---

lib/types/model.js

The latest swagger spec has changed the primitives a bit wrt: integer/number/float/long/etc. This seems to be the proper way to handle those changes. Might also want to do something with the byte and password formats of string.

Primitive types are stale

---

lib/types/operation.js

When creating a SwaggerClient with `useJQuery: true`, the Operations each inherit the `useJQuery` value. However, on execution, instead of using the value of `useJQuery` it looks for the value to be passed in via the Operation's options. Furthermore, it takes the value passed in at sets that on the Operation, having the side effect of overriding the correct value for the Operation's `useJQuery` setting.
This pull has the `Operation.prototype.execute` use the `useJQuery` setting inherited from the SwaggerClient by default, but if a value for `useJQuery` is passed in the Operation.prototype.execute parameters, it uses that value instead, but only for that single method execution.

Correctly use useJQuery from Client in Operation

---

lib/types/operation.js
test/operation.js
test/types.js

Fixes swagger-api/swagger-ui#1133.
operation#getType returns a string, which was fine for everything but
inline models, which until now couldn't be referenced.
opertation#getType now returns 'inline#123' for inline models, where 123
is the index of the inline model.
I've put in an array, operation#inlineModels, that keeps track of
inline models added via operation#addInlineModel.
To de-reference inline models, use operation#getInlineModel, passing it
the 'inline#123' string
operation#getSampleModelJson, uses the above.

ui#1133: add more support for inline schema's

---

package.json

This updates the project GitHub URL. Link on https://www.npmjs.com/package/swagger-client still points to https://github.com/swagger-api/swagger-client, how can I help to fix it?

Update git repository URL

---

bower.json

I am following up on #286 as the modifications are not done yet, but I would need Bower support quite soon.
Also #286 included the wrong mail file. This bower.json downloads the minimum set of files required for browser.

Add Bower support

---

lib/types/operation.js

Hi,
this is related and required by the swagger-api/swagger-ui#1121 PR in a context of default values for the array type parameters.
Additionally - enum definition at array items level as an option. This approach conforms either to Swagger Spec or to JSON Schema, so probably should be handled.
@webron: this is the #354 duplicate, now created against the develop_2.0 branch.
The #354 branch was created from develop_2.0 branch, I've only missed, that the master branch is proposed as default when creating any PR. Sorry for the inconvenience.
Best,
Waldek

Default value attribute as an array for array type parameters.

---

lib/spec-converter.js

Fix for handling basePath that start with 'https://'

Fix to handle https basePath

---

lib/types/model.js
test/models.js

Examples on top-level definitions are now included in the model.
See issue #409

Fix for #409: Top level example is included in model

---

.travis.yml
gulpfile.js
package.json
test/browser/driver.js
test/browser/servers.js
test/browser/test-v2.js
test/spec/v2/petstore.json

This pull should resolve #383. The test harness here borrows from the swagger-api/swagger-ui browser test harness. 
Currently, browser tests are wired separately from the non-browser tests, based on what I saw in the gulpfile (line 25, `paths.tests` explicitly ignores `test/browser/*.js`). To run browser tests, issue either `npm run browsertest` or `gulp browsertest`.

Test harness for running browser tests

---

browser/swagger-client.js

Hi there,
we're currently investigating using swagger as the primary means to document our APIs at XING. We really like swagger so far and see a lot of potential in it for us. You guys do an awesome job. 
During our tests with swagger we bumped into little things here and there. I just wanted to contribute a little bit back :-)
Our APIs are mostly Rails based and Rails seems to return responses  body containing whitespace on 201s, which results in a parser error. This little patch makes the client a little more robust against that.
I tried to write a test for that as well, but unfortunately I'm not a javascript crack and failed to succeed. I hope that's alright ^^

parseBody handle whitespace in responses

---

browser/swagger-client.js

I'm sure this is a very naive fix, but I just wanted to throw that out there unless someone has any better ideas

Don't warn when produces is "*/*".

---

lib/types/operation.js
test/request.js
test/spec/v2/petstore.json

Fix for an issue reported in swagger-ui project: (swagger DELETE requests changing to incorrect content type) https://github.com/swagger-api/swagger-ui/issues/1435
The code contains a skipped test for DELETE method with a body ( I'm not sure what is the best way to handle this... I'd need to research the structure of json/schemas and update mocks, I'm afraid it might take too long without a hint)
// This pull request is a part of a sample task by @webron.

Fix swagger-api/swagger-ui#1435

---

lib/types/operation.js

This is based on my reading of the 2.0 spec: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#operationObject says that the `schemes` in the operation override any `schemes` in the parent.

Set operation.schemes to the value of 'schemes' if set

---

lib/types/operation.js
test/help.js

Appends operations parameters to the `asCurl` method

Fixed #504: The `asCurl` method doesn't allow to set content type for response and request

---

lib/resolver.js
test/composition.js

Fix `allOf` to work as intended.
The example JSON we have:
```js
"definitions": {
"Parent": {
"properties": {
"hey": {
"type": "string"
}
}
},
"Child": {
"allOf": [
{
"$ref": "#/definitions/Parent"
},
{
"properties": {
"there": {
"type": "string"
}
}
}
]
},
"Grandchild": {
"allOf": [
{
"$ref": "#/definitions/Child"
},
{
"properties": {
"bob": {
"type": "string"
}
}
}
]
}
}
```
And in the Swagger UI now the model looks like (as should be):
```js
{
"grandchild": {
"hey": "string",
"there": "string",
"bob": "string"
},
"child": {
"hey": "string",
"there": "string"
},
"parent": {
"hey": "string"
}
}
```
instead of the previous (incorrect) result:
```js
{
"grandchild": {
"bob": "string"
},
"child": {
"hey": "string",
"there": "string"
},
"parent": {
"hey": "string",
"there": "string"
}
}
```

fix allOf support

---

browser/swagger-client.js

Avoid `too much recursion` errors with properties like:
"species": {
"type": "string",
"enum": [
null,
"cat",
"dog"
]
}
The [JSON Schema spec says for enums][1]:
> Elements in the array MAY be of any type, including null.
But they [aren't supported by Swagger 2.0][2], because [null isn't one
of Swagger 2's types][3].  This commit gives a more obvious hint about
that.  It would be nice to have [clarification in the spec][2] so we
could link to tidier docs than the GitHub issue too.
It would be nice if I could point to line numbers (or the chain of
keys?) to find the broken entry in the parsed spec, but it doesn't
seem like that information is available in `resolveAllOf` and I'm not
clear enough on the larger picture here to know where that would plug
in.
Anyway, this PR should help avoid …

browser/swagger-client.js: Throw errors for null types

---

lib/auth.js

If you have several apiKey authentications defined (like key+secret),
they were not applied both to the Request, because of
status = status || !!auth.apply(obj);
Once status becomes `true` after applying the first security rule, the
seconds (and all next ones) are ignored, as logic expression was
errorneous.
Fixing it, by changing OR into AND, as we want to return `false` if ANY
of the auths were failing, second of all making `auth.apply(obj)` be
executed always, by extracting the statement into separate line.

Fix inability to apply multiple apiKey authentications

---

lib/client.js

When an API supports multiple schemes like below, this client arbitrarily picks the first entry.  This PR adds the ability for the client to be initialized with a specific scheme.
```
"schemes": [
"http",
"https"
]
```
To initialize with a specific scheme, do this:
```
var client = require('swagger-client');
var swagger = new client({
url: 'http://petstore.swagger.io/v2/swagger.json',
scheme: 'https',
success: function() {
// do something
}
});```

Ability to choose scheme on client init..

---

lib/resolver.js

I have tried to use swagger-js in my Ember.js project. Swagger fails on reading json and raises "Maximum call stack size exceeded" error. The reason is [Ember's prototype extension](http://guides.emberjs.com/v2.0.0/configuring-ember/disabling-prototype-extensions/). I have added `.hasOwnProperty` check, it solves the problem.

add hasOwnProperty check in resolver

---

lib/schema-markup.js

If a property is type: boolean, allow its example to be false.
````javascript
{
"description": "This is a boolean property",
"type": "boolean",
"example": false
}
````

Allow schema example to be false

---

lib/client.js

for loading the ArangoDB swagger-ui my browser takes 30s. 
I've tried adding the swagger supplied throbber.gif, but that won't animate while the swagger is working. Probably some counters for this.progress would be better.

Add a warning to the user, that this may take a while.

---

lib/client.js
test/client.js

Add "title" to the list `reservedClientTags` to prevent overriding of `self.title` string with an operation group object.
Fix https://github.com/swagger-api/swagger-ui/issues/1615
@webron could you please review?
I did not include the result of `gulp build` as the change-set is quite large, but I am ok to do that if you like.

Fix support for "title" tag

---

README.md

The 'name' argument has been deprecated.

Remove <name> in basic auth example in README

---

lib/types/operation.js

Security parameter used in `Operation.execute`, but not in `Operation.asCurl`. Without this parameter `SwaggerAuthorizations` will apply all available security rules ignoring actual settings from Swagger JSON for Curl string generation. See https://github.com/swagger-api/swagger-js/blob/master/lib/auth.js#L43

Missed security parameter

---

lib/spec-converter.js
test/compat/converter.js
test/spec/v1/single.json

The || logic here was faulty and always resolved to true. If a
spec came through with a type of 'object', the definition inside
spec-converter was returned as '#/definitions/undefined'.
This manifested in a *lot* of extra calls to the `swagger.json` endpoint when the client booted. For example, before this patch:
```
GET/explorer/resources/chat                2015.08.28 13:51:56.602
GET/explorer/resources/apiKey              2015.08.28 13:51:56.606
GET/explorer/resources/apiKeyConstraints   2015.08.28 13:51:56.608
GET/explorer/resources/execution           2015.08.28 13:51:56.609
GET/explorer/resources/instrument          2015.08.28 13:51:56.611
GET/explorer/resources/order               2015.08.28 13:51:56.612
GET/explorer/resources/orderBook           2015.08.28 13:51:56.617 …
```

Fix spec conversion with anonymous array/object types.

---

lib/resolver.js
test/resolver.js

fixes #491 
Shared parameters (`swagger.parameters`) will resolve through references to `#/parameters/{paramName}`.  Shared parameters at the path level will be resolved and removed from the path object after resolution.

adds tests, support for top-level shared and path-level parameters

---

lib/auth.js

cookiejar 2.0.1 code:
`exports.CookieJar = CookieJar;`
Error before fixing:
```
/usr/local/bin/node swa.js
/Users/zengxian/workspace/jike-app-service/node_modules/swagger-client/lib/auth.js:102
obj.cookieJar = obj.cookieJar || new CookieJar();
^
TypeError: CookieJar is not a function
at CookieAuthorization.apply (/Users/zengxian/workspace/jike-app-service/node_modules/swagger-client/lib/auth.js:102:36)
at /Users/zengxian/workspace/jike-app-service/node_modules/swagger-client/lib/auth.js:62:28
at /Users/zengxian/workspace/jike-app-service/node_modules/lodash-compat/internal/createBaseFor.js:19:11
at baseForOwn (/Users/zengxian/workspace/jike-app-service/node_modules/lodash-compat/internal/baseForOwn.js:14:10)
at /Users/zengxian/workspace/jike-app-service/node_modules/lodash-compat/internal/ …
```

fix CookieJar reference

---

lib/client.js

Instead of calling failure and then throwing unconditionally, default to simply throwing, but allow the user to override this behavior in the provided callback.
This is currently broken AFAICT - the throw in SwaggerClient.prototype.fail() can't be caught. If I'm wrong, please let me know.
Not really sure how to test this because I can't catch the failure.

Don't throw when user defines a failure function.

---

lib/schema-markup.js

mentioned in
https://github.com/swagger-api/swagger-ui/issues/1248
https://github.com/swagger-api/swagger-ui/issues/1231
A "read only" string is added to the properties. Additional it is possible to possible to hide the properties via css in specific methods

Fix for readOnly-issue

---

lib/types/operation.js
test/compat/request.js
test/help.js
test/request.js

We have a scenario where we have a "!" character inside our JSON request data:
```
{
"username": "alice",
"password": "cooper!00"
}
```
Swagger's `asCurl` method renders this as follows:
```
curl -X POST -d "{
\"username\": \"alice\",
\"password\": \"cooper!00\"
}" https://example.com/api
```
bash now tries to interpret the "!" here, which results in this error: `-bash: !00: event not found`.
There's no way to escape "!" in double quotes so we suggest the following output:
```
curl -X POST -d '{
"username": "alice",
"password": "cooper!00"
}' https://example.com/api
```
Does the trick and is also much easier to read.
Would you accept this PR? It fixes the problem and updates the corresponding 2 tests.

Output curl --data in single quotes (instead of double quotes)

---

lib/types/operation.js
test/compat/request.js
test/help.js
test/request.js

Now all the curl arguments are using single quotes for consistency reasons:
```
curl -X POST --header 'Content-Type: text/html' -d '{
"username": "alice",
"password": "cooper!00"
}' 'https://example.com/api'
```
See #627

Output curl URL in single quotes

---

lib/resolver.js
test/composition.js

The main fix is to ensure that the receiving object's fields aren't overwritten by the merged in attributes

Several allOf related fixes

---

lib/client.js
lib/http.js
lib/types/operation.js

Setting `enableCookies` to true in the options of a new SwaggerClient or in the options object of an operation makes the browser include the cookies and other HTTP credentials in it's requests.
Naming the option 'enableCookies' as suggested by user tonytam in IRC.
More information about sending credentials: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Requests_with_credentials 
--
I've not written tests and not made the jQuery client honor the option. 
Is this the way to go?

enableCookies option in client and operations

---

lib/resolver.js
test/resolver.js

For inhered classes new class definition is processed as inline. That definition is localized in the current file so root element url should not be added for it.

#666 fix for local base model properties

---

README.md

Inconsistent naming conventions in the examples leads to confusion. Especially problematic was the section about adding an API key, since both the client instance and constructor were variables called 'client' (which doesn't work in practice, and makes it unclear where the nested ApiKeyAuthorization function lives).

Updated variable naming for clarity and consistency

---

lib/resolver.js

This additional check prevents invocation of `indexOf()` on possible null `ref` variable and improves therefore error messaging for malformed yaml files. 
Before:
```
Cannot read property 'indexOf' of null
```
After:
```
Uncaught TypeError: Swagger 2.0 does not support null types
```

an additional null check added

---

lib/spec-converter.js

This patch addresses issues raised in swagger-api/swagger-js#699

set schema.required instead of schema.enum for required properties

---

lib/resolver.js

I'm using[ swagger-ui](https://github.com/swagger-api/swagger-ui) ([issue in swagger-ui repo](https://github.com/swagger-api/swagger-ui/issues/1925#issuecomment-189260645)) which uses swagger-client. I want to display the title of objects but it only outputs 'inline_model' as title. I found this quick fix in swagger-client but I'm not sure which project is related to the bug. 
Maybe someone could help?

quick fix for object title in swagger-ui

---

lib/types/operation.js

Arrays of enums as method parameters stop working with current swagger. They ware broken after clean-up in that commit #198 e30ceecca72409576448410e5c19834b0f5e6abb. Currently values of enums are not taken from item element when array is being used. As the result the text area appear not the select.
The swagger definition:
```
{
"swagger": "2.0",
"basePath": "/v1/api",
"paths": {
"/article": {
"get": {
"parameters": [
{
"name": "enumArrayParameter",
"in": "query",
"description": "Select for enum values.",
"required": false,
"type": "array",
"items": {
"type": "string",
"enum": [
"OPTION_1",
"OPTION_2",
"OPTION_3"
]
},
"collectionFormat": "multi"
}    
]
}
}
} 
}
```
Current (broken) look of swagger-ui:
Expected look of swagger-ui (after fix and before clean-up):

Fix for array parameter with defined enums values

---

lib/resolver.js
test/resolver.js

At present, the following response block will not currently resolve the Pet ref:
```
responses:
200:
description: "successful operation"
schema:
type: "array"
items:
$ref: "#/definitions/Pet"
```
This PR adds support for automatically resolving these type of references in responses where the $ref is part of an array response.

Resolve refs in responses which contain arrays

---

lib/types/operation.js
test/operation.js

fixed array params with collectionFormat tsv on query and path to urlencode tab as %09. fixed tests. also added proper test for collectionFormat multi.

fix to issue  #769 - tsv arrays seem broken but easy to fix

---

lib/types/operation.js
test/operation.js

In the `urlify` function, if `this.path` contains a URL fragment, it blindly adds a URL query _after_ the URL fragment, which is incorrect.
This fix simply removes the URL fragment, before building the URL, because I don't think a user of swagger-js would have a need for URL fragments.
I use URL fragments in paths used with Swagger-UI, as a work-around to overload endpoints, so it would be great to get this fix in for Swagger UI 2.1.5 to incorporate.

urlify function now removes URL fragment before building URL

---

lib/types/operation.js
test/request.js

We have some DELETE endpoints that accept FormData, but sending a body was only working for JSON.

Send formData on DELETE & add test.

---

lib/client.js
lib/http.js
lib/types/operation.js
test/client.js
test/request.js

I am using swaggerUi with the `useJQuery` option set to true to be able to use our jquery polyfill for older browsers.
Currently in the JQueryHttpClient `cache: false` is hardcoded in ajax requests which results in all requests to go out and also appends a timestamp to query parameters to bust cache. This pull request tries to expose the option (with a default value of false on both the client and operations) for users to be able to set it to true (default jquery behavior). In each file I tried to do things the way they were already done.

Allow users to turn off jquery cache busting for get and head requests

---

lib/client.js

Client.js needed a `typeof(window) !== 'undefined'` in order to prevent browserless testing in Mocha (and probably other testing suites) from throwing an error. Closes #804

Adds typeof check to window check

---

lib/client.js

If swagger-js is configured to load a local specification using the `spec` property (rather than a remote one using the `url` property), the loading message is currently:
```
fetching resource list: undefined; Please wait.
```
which is quite ugly.
This PR changes this to:
```
fetching resource list; Please wait.
```
when the `spec` property is defined.

Add "fetching resource list" message for local (non-URL) spec

---

test/resolver.js
test/spec/v2/externalRefInAllOf.json

Based on issue raised on swagger-ui (#2304) [https://github.com/swagger-api/swagger-ui/issues/2304 ](url), as suggested I added a test case 2 with $ref within an allOf construct that does not resolve correctly within swagger-ui.

add test to resolve $ref within allOf construct

---

lib/client.js
lib/http.js
lib/resolver.js
lib/spec-converter.js
lib/types/operation.js
test/client.js
test/operation.js

Adds support for configuring timeouts on spec and operation requests.
`timeout` option:
- configured in `ms` for requests at the client and operation level
- pass as option when creating a client to set a timeout for all requests
- pass as an option when executing an operation to set a timeout for a specific request
`fetchSpecTimeout` option:
-  option will override `timeout` when specified
- when a value is passed to`timeout`,  pass `null` or `false` to for `fetchSpecTimeout` use agent default when fetching a spec
Will fail with an informative message when a timeout occurs (tested with `superagent` in unit tests and manually in the browser with jQuery's `$.ajax`)
Possible nice-to-haves in the future:
- `x-timeout` vendor extension to specify timeouts at the spec, route, or operation …

Timeout support

---

lib/types/operation.js
test/headers.js

Allows header parameters to be passed insensitive to case, conforming to [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)

make header parameters case insensitive

---

lib/resolver.js
test/resolver.js
test/spec/v2/relativeToRoot.json

My spec heavily uses refs like `/api/1/something.json` without domain part, but not relative like `./some.json` or `../../some.json`. Before this fix swagger UI did fail with exception and become unusable.

Fix {$ref: "/domain/based/path/"} resolving

---

lib/client.js

The protocol is incorrectly assigned here - window.location.scheme is not a thing. Please create a new release as v2.1.19 is broken with a bug where a request sent from a https swagger-ui is calling an http endpoint which the browser disallows because of security reasons.

Fixes incorrect protocol bug

---

lib/client.js
lib/http.js

Node, by default, uses a hardcoded list of CAs instead of the system CAs. In order to use a CA that is not on that list, you have to hack it into the list by patching the global https agent. Unfortunately, superagent explicitly turns off the global agent which makes patching it a no-op. So this PR adds the ability to supply the CA for superagent as an option.

add support for adding a custom http(s) agent

---

lib/http.js

The merged fix for https://github.com/swagger-api/swagger-js/issues/877 doesn't work since actually in older chrome, safari and IE there's no way to get access to FormData contents ( http://stackoverflow.com/a/33821488/1924141 ) however `SuperAgent` supports getting a ready FormData, so could we just give it to it?
This fixes basic POST support in Safari and older chrome, but I'm not sure if it breaks some other use-cases since the `FormData` branches seem to be not covered with unit tests

Use superagent.send to avoid mangling FormData

---

README.md
lib/http.js

add support of CA for superagent as an options object (not https.Agent instance). For some resons implementation in previous pull request https://github.com/swagger-api/swagger-js/pull/875, work only for first request, next ones don't use agent  and fails with 403 (more details can be fount at previous PR discussion).

Using custom http(s) agent

---

lib/client.js

Currently, in combination with SwaggerUI, the enableCookies information set in the SwaggerUI options is lost because of the SwaggerClient. This should not happen because in the SwaggerUI project this option is used to set the "xhr.withCredentials" flag. However, in the current version this "enableCookies" flag can never be true.

Pass enableCookies option from SwaggerClient options to SwaggerHttp

---

gulpfile.js
package.json

The sourcemaps in the browserified libraries were incorrect due to the addition
of the header. We can fix this using gulp-sourcemaps to export correct
sourcemaps.

Fix errors in embedded sourcemaps

---

lib/resolver.js

Had the problem that in the application where I use this library all `Array` objects get enriched with some extra methods. So when using the `for...in` I always had the problem hat also these extra methods where added to the `parameters` array leading to a recursion problem in the end (like in #29 or #773). Would be great if you could merge this. I could also bring this to the browser version. Then we would need to check if the `Array.forEach` method is available before (e.g. IE8 does not have it).

Use Array.forEach instead of for...in

---

README.md
lib/http.js
lib/types/operation.js

Even though the current API supports passing in a different http client, you may want to just use a different instance of superagent.  For our use case, we have a number of plugins that get wired up into superagent so we want to use that instead.

Adds ability to override request agent

---

lib/client.js

The issue due to the mutated scopes popped up in Swagger-UI: https://github.com/swagger-api/swagger-ui/issues/2483
I am not sure if this is a **correct** solution, but it works for me.
/cc @fehguy @janslow

Fixed unnecessary scopes mutation

---

lib/client.js

chrome swagger ui extension scheme bug fixed. If chromw extension ui is being used then swagger doc scheme will be set

chrome swagger ui extension scheme bug fixed. If chromw extension ui is being used then swagger doc scheme will be set

---

README.md

Fixed typos in Authorization section of README.md

---

lib/client.js

modified lib/client.js to use protocol from loading the definition if schemes is not defined
#931

issue 931 fix

---

lib/types/operation.js
test/operation.js

Re: the discussion here
https://github.com/swagger-api/swagger-js/pull/847
I've made this an extensible parameter. Will this work?
Thanks!

Allow x-escape to be part of a parameter to prevent urlencoding.

---

README.md

Hi,
When I was browsing docs of swagger-js, I found small markdown typo. Tiny piece, but now looks better :-)

Added missing markdown js block opening to README.md

---

lib/types/operation.js
test/client.js

Hi guys, 
We pulled in the latest version 2.1.31 and found a breaking change from 2.1.2x
It seems to be converting `bar=0` into `bar=`, I added a test to show with a sample parameter and resulting url 
```
$ npm test
> swagger-client@2.1.31 test /Users/gina/git/swagger-js
> gulp test
[12:52:09] Using gulpfile ~/git/swagger-js/gulpfile.js
[12:52:09] Starting 'test'...
SwaggerClient
1) doesnt remove 0 from query params
0 passing (85ms)
1 failing
1) SwaggerClient doesnt remove 0 from query params:
AssertionError: 'http://localhost:8000/double/foo?bar=' === 'http://localhost:8000/double/foo?bar=0'
+ expected - actual
-http://localhost:8000/double/foo?bar=
+http://localhost:8000/double/foo?bar=0
```
If the value is not falsy, (for example 1) the test passes we found that …

shouldnt remove 0 values from query params

---

lib/types/operation.js
test/help.js
test/request.js

Fix for #947 & #948 - curl changes - 
- only form encode form content type data (it doesn't make sense to URL encode values in JSON data)
- still ensure apostrophe ' is encoded via unicode if not URL encoding
- remove the new line patterns that prevent cURL commands from executing (for me at least)
- ensure @ is literal outside of file usage (--data-raw usage - 'post body with special chars' use case) - an alternative to this might have been unicode
- fix file submission support
Some test expectations were changed:
- I wouldn't expect the values in my JSON to be received with URL encoding on the server
- I wouldn't expect JS escaping to happen via cURL, this should be the responsibility of the server and the client rendering any feedback.
I have not regenerated the swagger-client.js and …

Fix for #947 & #948 - cURL changes

---

lib/spec-converter.js

specConverter not use client from options, I fix this.

fix usage options.client in specConverter

---

lib/http.js

This consider the case where the request body is a buffer, the client is sending raw data to the server and superagent will send the buffer correctly.

Buffer object in request body

---

src/execute.js
test/execute.js

The header broke the CORS contract, which was evident in the petstore example.
This PR likely breaks the oAuth security flow, which relied on this header. @bodnia, could you let me know how to test the oAuth flow, the reason we added this header in the first place? We may need to find an alternative

Remove access-control-allow-origin from all requests

---

.gitignore
webpack.bundle.config.js
webpack.common.js

This makes it work with <script/>
The standalone bundle now lives in `browser/swagger-client.js` which matches 2.x
It also expose `SwaggerClient` on the window object ( to be precise, it does so via UMD ).
ping @webron

fix standalone bundle... now points to where 2.x did.

---

src/execute.js
src/index.js
test/index.js

helps with: https://github.com/swagger-api/swagger-js/issues/971
This is the first pass at adding back authorizations to the instance methods.
```javascript
Swagger({ 
spec,
authorizations: {
someApiKey: 'hello',
someBasicAuth: { username: 'foo', password: 'bar' },
someOAuth: { token: { access_token: 'foo bar' } }
}
}).then( client => {
client.apis.pet.addPet() // If this has any `securities`... they'll be added to the request
})
```
Next step is to create classes for the above. 
PS: I don't see cookie authorizations... not sure if we can easily implement.
ping @webron, @fehguy

add open object authorizations

---

src/execute.js
src/helpers.js
test/execute.js

Fixes https://github.com/swagger-api/swagger-js/issues/965

Merge Path and Operation parameters

---

src/execute.js
test/execute.js
test/index.js

follow up to https://github.com/swagger-api/swagger-js/pull/970
----------------------------
For issue https://github.com/swagger-api/swagger-ui/issues/2744
When Swagger UI is hosted behind user authorization(eg. http basic), the user enters username and password, and gets a cookie to access Swagger UI.
However when the swagger spec is downloaded from the same origin, the cookies are not sent in the request.
Also see https://github.com/github/fetch#sending-cookies

send cookies

---

package.json
src/resolver.js
src/specmap/lib/context-tree.js
src/specmap/lib/refs.js
test/index-authorizations.js
test/index.js
test/resolver.js
test/specmap/context-tree.js

See https://github.com/swagger-api/swagger-ui/issues/2767#issuecomment-289913619
There are 2 problems:
* SwaggerUI passes in the wrong parameter name. To avoid having to change SwaggerUI, I change SwaggerJS to allow both names (because the correct name is used both internally and possibly other clients). We should clean up interface anyway in the next refactor.
* There's a certain behavior in the context-tree component that causes the baseDoc to be clear for all but the first reference. I talked to Josh and it was confirmed as a bug. Already add failed test and fix it.
I've tested the latest code with UI & the reported spec, it works without problem.  (Also, unrelated, but I also fixed some failed tests after merging from upstream master, we should enforce code change better and avoid …

Fix problem cannot resolve relative references

---

src/index.js
src/resolver.js
test/http.js
test/index.js

xmock doesn't support `fetch` that makes it difficult to do end to end http tests.
In the meantime we can mock out the `http` function. It was possible to do this in the static functions... this PR adds it to the resolve _method_
NOTE: It also skips the network tests.

Allow mocking http function

---

src/http.js
test/http.js

This PR implements the fix requested in https://github.com/swagger-api/swagger-js/issues/979#issuecomment-290249977 by using `.buffer()` to get the binary response body when `.blob()` is not available, which occurs with `node-fetch` prior to version 2 (currently in alpha).
It also fixes the existing test for `serializeRes` which would always pass due to not returning the Promise value it created.  If you would prefer this to be split into a separate PR, let me know.
Thanks,
Kevin

Use .buffer() for binary responses when .blob() is not available

---

src/execute.js
test/execute.js

When user API specification contains custom header input parameter which is optional (required field equals false) and user doesn't provide value for it then client sends header with value of undefined. Example:
```
POST http://localhost:8080/example/url HTTP/1.1
Content-Length: 2
Content-Type: application/json
X-Customer-Header: undefined
{}
```
When header is optional and allowEmptyValue is set to false then header should not be sent. Example:
```
POST http://localhost:8080/example/url HTTP/1.1
Content-Length: 2
Content-Type: application/json
{}
```
When header is optional and allowEmptyValue is set to true then header should be sent with empty value. Example:
```
POST http://localhost:8080/example/url HTTP/1.1
Content-Length: 2
Content-Type: application/json
{}
```
According to …

Fixed sending header parameters when value is not set.

---

src/http.js
src/resolver.js
test/client.js
test/index.js

This fixes #1014 and #1002.
@fehguy please take a look. One thing of note: because fetch is shared for both spec loading & operation execution, the change affects operations, see https://github.com/swagger-api/swagger-js/compare/master...buunguyen:fix-error-handling-2?expand=1#diff-7e3bd8e7059a21bfd255649cbfc84b33R130 (must change from `then` to `catch`). This can be considered a breaking change from semver perspective. UI/editor might need to change.

Fix error handling

---

src/specmap/lib/refs.js
test/index.js

"Fixes" https://github.com/swagger-api/swagger-ui/issues/2889 and https://github.com/swagger-api/swagger-ui/issues/2923.

Fix issue circular ref not resolved if baseDoc is provided

---

src/execute.js
test/execute.js

and NOT in buildRequest, so as to allow other code to modify the body,
before finally getting processed by execute

stringify request.body in #execute

---

src/resolver.js
src/specmap/lib/refs.js
test/index.js

Fix root cause of https://github.com/swagger-api/swagger-ui/issues/2892#event-1064243022. Pretty subtle bug. The fix isn't elegant, but that's to avoid changing the internal structure too much, better leave that for more significant refactoring.
cc @webron @shockey

Fix cyclic ref problem when baseDoc is specified

---

src/execute.js
test/execute.js

The token type is case insensitive.
The authorization scheme of the Authorization header is case sensitive.
Fixes #1040

Do not depend the Authorization header on the token type.

---

src/execute.js
test/execute.js

Ensure we don't stringify FormData ( ie: files ) bodies. From https://github.com/swagger-api/swagger-js/pull/1034#event-1066274328
NOTE:
While testing, I bumped into a regression... file uploads were broken :/
I verified this works in the awesome commercial product SwaggerHub, which I think is super cool.
But doesn't work in editor.swagger.io ( also cool ).
```yaml
swagger: '2.0'
info:
version: "1.0.0"
description: Test file uploads
title: Test File Uploads
host: httpbin.org
schemes:
- https
paths:
/post:
post:
consumes:
- multipart/form-data
produces:
- application/json
parameters:
- name: "file"
in: "formData"
description: "file to upload"
type: "file"
responses:
200: 
description: ok
```
The spec I used to test. 
Anywhoo, this PR should fix it ( I say should, as I don't have time to …

Ensure we don't stringify FormData, and fix a multipart regression.

---

src/http.js

Change the import method for fetch (Recommended by : https://github.com/matthew-andrews/isomorphic-fetch).
I have a problem with the current exported `fetch` of `isomorphic-fetch` : 
I want to mock fetch for unit testing (Not just swagger part), and actually its impossible because of webpack.
Ex : 
This es6 code :
```js
import fetch from 'isomorphic-fetch'
```
will be transpiled by babel, transformed by webpack and the result something like this : 
```js
var _isomorphicFetch2 = _interopRequireDefault(_isomorphicFetch);
var _isomorphicFetch = __webpack_require__(15);
// And the webpack require =>
/* 15 */
/***/ (function(module, exports) {
module.exports = require("isomorphic-fetch");
/***/ })
```
If we look at es6 swagger code for fetch
```js
return fetch(request.url, request).then((res) …
```

[Fix] Wrong isomorphic-fetch import

---

package.json

Changes mask for `fast-json-patch` dependency from `1.*.*` to `1.1.*`.
Workaround for https://github.com/Starcounter-Jack/JSON-Patch/issues/178

Tighten fast-json-patch version range

---

src/helpers.js
test/helpers.js

Modifies `getOperationRaw` to support matching an operation by raw operationId (for https://github.com/swagger-api/swagger-ui/issues/3146).
Also, modifies `findOperation` to return an `null` instead of `undefined` when an operation can't be found - to indicate intentionally returning nothing.

helpers/getOperationRaw: find operations with escapable characters

---

src/resolver.js

Adds [credentials: same-origin](https://github.com/github/fetch#sending-cookies) to resolved fetch options. This will instruct the browser to send cookies and authorization headers when fetching external definitions.
Existing issue: https://github.com/swagger-api/swagger-js/issues/1025
Symptom issue in swagger-ui: https://github.com/swagger-api/swagger-ui/issues/3220
Note on testing: Since these tests do not run in a browser, it would be difficult to assert that cookies are being set properly in a test. We could however create a spy that ensures that `fetch` is getting the `credentials: same-origin` option passed to it. 
@shockey

Add same-origin credentials policy to makeFetchJSON

---

src/http.js
test/http.js

first vs last
```
function shouldDownloadAsTextOrig(contentType) {
return /json/.test(contentType) ||
/xml/.test(contentType) ||
/yaml/.test(contentType) ||
/text/.test(contentType)
}
/*
Orig|json x 11,477,916 ops/sec ±0.75% (91 runs sampled)
Orig|xml x 7,497,474 ops/sec ±0.52% (97 runs sampled)
Orig|yaml x 5,051,156 ops/sec ±0.68% (94 runs sampled)
Orig|text x 4,224,534 ops/sec ±0.39% (96 runs sampled)
*/
function shouldDownloadAsTextOne(contentType = "") {
return ["json", "xml", "yaml", "text"].some(str => contentType.includes(str))
}
/*
One|json x 6,393,355 ops/sec ±0.62% (94 runs sampled)
One|xml x 4,242,619 ops/sec ±0.89% (94 runs sampled)
One|yaml x 2,880,927 ops/sec ±0.35% (95 runs sampled)
One|text x 2,286,908 ops/sec ±0.61% (93 runs sampled)
*/
function …
```

Change the regex, increase performance increadibly :D

---

src/http.js
test/http.js

Currently, when passing a boolean query parameter with a value of `false` to `http`, the following error surfaces:
```
TypeError: value.map is not a function
at formatValue (src/http.js:171:16)
at src/http.js:187:36
at Array.reduce (native)
at encodeFormOrQuery (src/http.js:182:42)
at Context.<anonymous> (test/http.js:218:14)
```
This PR resolves this error by adding a boolean type check in the `formatValue` function.

Allow false query parameters

---

src/specmap/lib/index.js
test/specmap/all-of.js

Fix and test for swagger-ui #3328 - https://github.com/swagger-api/swagger-ui/issues/3328
Added manual logic to merge arrays after calling deepExtend within `mergeDeep` function.

Manually merge arrays inside mergeDeep

---

src/specmap/index.js
test/specmap/index.js

Fixes https://github.com/swagger-api/swagger-ui/issues/3376.
Check to make sure properties is the root (first) instance of properties before running plugins.
Added a test to ensure new functionality works.

Fixes #3376 - Keyword properties fix

---

package.json

Currently, `npm run build` fails on Windows - it chokes on `NODE_ENV=production`, because Windows requires the `set` keyword to set environment variables: `set NODE_ENV=production`. See also: https://github.com/swagger-api/swagger-js/issues/1066#issuecomment-304204774.
This PR adds [cross-env](https://www.npmjs.com/package/cross-env) to make environment variable assignment work on both Windows and *nix.

Use cross-env to make build scripts Windows-compatible

---

src/specmap/lib/all-of.js
test/specmap/all-of.js

Fixes #1129 
Should also fix the following swagger-ui issues:
https://github.com/swagger-api/swagger-ui/issues/2946
https://github.com/swagger-api/swagger-ui/issues/3490
https://github.com/swagger-api/swagger-ui/issues/3342
https://github.com/swagger-api/swagger-ui/issues/3127
https://github.com/swagger-api/swagger-ui/issues/3093
and possibly others...
Added a patch at the end of the `allOf` plugin to make sure the original values for the definition are merged back into the result of the `allOf`. This includes the `$$ref` value. For definitions that did not originally include `$$ref` values, we make sure the result of `allOf` does not have a `$$ref` value.
I wrote a test for the new functionality, but during test runs (any test, not just mine), the `$$ref` value that is set during the …

Fixes #1129 - allOf fix for $$ref values

---

src/execute.js
test/index.js

When security definitions are present in the spec and an API call is made without providing an `access_token` value, the resulting auth2 authorization header is invalid: `authorization: Bearer `. 
This PR makes sure an oauth2 authorization header is added only if `access_token` has a value.

Fix empty oAuth2 Bearer token added to req header

---

src/execute/index.js
test/oas3/execute/main.js

Fixes https://github.com/swagger-api/swagger-ui/issues/3681.

Fix OAS3 context url inference

---

package.json

This is a temporary fix to lock the version of json-fast-patch to one which doesn't spam the console.
- https://github.com/swagger-api/swagger-js/issues/1143

Temporary fix for console spam

---

package.json

`fetch-mock@5.13.0` is blowing up our tests (25 failing, see https://travis-ci.org/swagger-api/swagger-js/jobs/285076321).
This PR tightens the version constraint on it, in order to avoid the bad version.

Tighten `fetch-mock` version constraint

---

src/helpers.js
src/index.js

Fixes #1152.
This PR:
- migrates `String().startsWith` ES6 method usage to lodash's `startsWith` function
- loosens `isOAS3` helper to match `openapi: 3*` instead of `3.0.0*`

Refactor `startsWith` usage for IE11 compatibility

---

src/execute/swagger2/build-request.js
test/index-authorizations.js

Fixes #1155 
Pass 'Bearer' if the token_type property equals 'bearer' or is falsy.
Fixes original issue found in UI: https://github.com/swagger-api/swagger-ui/issues/3594

Fixes #1155

---

src/execute/index.js
test/oas3/execute/main.js

Fixes https://github.com/swagger-api/swagger-ui/issues/3791.
This is an edge case that doesn't bubble up for every OAS 3.0 definition that lacks a `servers` definition. A request that has a `server` provided, but no `servers`, were causing this.

OAS3 baseUrl TypeError

---

src/index.js
src/resolver.js
test/index.js

Fixes https://github.com/swagger-api/swagger-ui/issues/3763.
This PR:
- Adds interceptors to Swagger-Client spec downloads
- Note: Swagger-UI already had this, since it defines its own spec download function, then gives the resulting object to Swagger-Client.
- Adds interceptors to special $ref fetches
- Note: the $ref docCache is alive and well, so `1 ref !== 1 request`.
- Sets the `req.loadSpec` flag on spec and ref requests
- Adds tests for the above functionality

Interceptors for $ref download

---

package.json

Per the conversation in #1148, `fetch-mock` no longer needs to be constrained to `5.12`.

Loosen fetch-mock version constraint

---

package.json
src/execute/index.js
src/execute/oas3/build-request.js
src/execute/oas3/parameter-builders.js
src/execute/swagger2/build-request.js
test/http.js
test/oas3/execute/authorization.js

This PR adds support for the following types of OpenAPI 3.0 security schemes:
- HTTP Basic
- HTTP Bearer
- OAuth2 Authorization Code
- OAuth2 Implicit
- OAuth2 Password
- OAuth2 Multiple Flows
- apiKey Header
- apiKey Query
There's a new `req.cookies` convenience key in `buildRequest`, but for now it's only useful in Node environments. Browsers do not allow arbitrary control of the `Cookie` header (see #1163).

OAS 3.0 Authorization

---

src/execute/index.js
test/execute/baseurl.js
test/oas3/execute/main.js

This PR modifies the Swagger 2.0 and OpenAPI 3.0 base url constructors to _not_ bail out if they cannot compute a scheme and host for the request.
@garywong89 brought this to my attention.
Without this PR, Swagger-Client will still generate a relative URL based on the path of the operation being executed, but won't attach a Swagger 2.0 basePath, or an OpenAPI 3.0 relative server path.
In order to solve this, I wrote failing tests for the Swagger 2.0 and OpenAPI 3.0 baseUrl constructors.

Generate relative base url if we can't make an absolute one

---

package.json

This allows the package to use the compatible range of lodash versions
Part of #1165, allows to reduce the bundle size when swagger-client is used as a part of bigger application
I ran `yarn install` and it worked

loosen lodash version constraint to major version 4

---

README.md
package.json

* `npm run build-dev` will create a non-minified `dist/index.js`
* This makes debugging possible and stack traces nicer
* Also, docs.
* Added a script in `package.json`
* updated `README.md`
* This issue was found when trying to debug https://github.com/swagger-api/swagger-js/issues/1171
* there was no way to easily create a `dist/index.js` for debugging.
* Run from the command line and tested with my app
Special thanks: https://stackoverflow.com/a/43308463/185799

add `npm run build-dev` target

---

test/client.js
test/data/petstore.yaml

Adds tests that highlight an issue in #1175.

Enable some skipped client tests; add tests for missing `Content-Type`

---

src/helpers.js

No report for this bug, but I ran into it today.

Don't try to access operation.operationId if operation isn't an object

---

src/http.js

Check the content-type of response and use appropriate parser: `js-yaml`, json, or no parser.
As described in #1165 even if one doesn’t use YAML at all, providing the spec via JSON object and using JSON to talk to backend, the swagger-client still uses `js-yaml` to parse responses. The downside to that approach is that one cannot forcefully remove `js-yaml` from Webpack bundle. 
If someone however have been using invalid JSON in the responses, this change will break things. Apparently the JSON parser of `js-yaml` is quite relaxed and handles even invalid JSON like this `{"123": NULL}`. It is your call whether to treat this as a breaking change or not.
`npm test` has passed

only use YAML parser for YAML responses

---

package.json
src/execute/oas3/parameter-builders.js
src/execute/oas3/style-serializer.js
test/oas3/execute/style-explode.js

This PR covers some missed cases for considering OAS 3.0's `Parameter.allowReserved`, and adds tests for the same.
Fixes https://github.com/swagger-api/swagger-ui/issues/3817.
- I added new tests 😄

Address issues with allowReserved

---

src/http.js

Check the content-type of response and use JSON parser only for `application/json`
As described in #1165 even if one doesn’t use YAML at all, providing the spec via JSON object and using JSON to talk to backend, the swagger-client still uses js-yaml to parse responses. The downside to that approach is that one cannot forcefully remove js-yaml from Webpack bundle.
If someone however have been using invalid JSON in the responses, this change will break things. Apparently the JSON parser of js-yaml is quite relaxed and handles even invalid JSON like this {"123": NULL}. It is your call whether to treat this as a breaking change or not.
`npm test` has passed

detect JSON by provided content-type instead of content check

---

src/execute/oas3/build-request.js
test/oas3/execute/main.js

Stringify object values in urlencoded bodies before serialization of the values.
Fixes https://github.com/swagger-api/swagger-ui/issues/3788.
Added a unit test.

Stringify object values before serialization

---

src/specmap/index.js

See #1150. Adds a 'per-patch' lookaside to the `traverse` method within `createKeyBasedPlugin`.
Previously, a `$ref` would be traversed multiple times during spec resolution. This change allows `$ref`s to be resolved once and prevents future unnecessary revisits.
Fixes #1150 - but still some questions about handling `allOf` resolution that may be handled in another PR.
All tests appear to pass - unsure if additional tests are required or need to be added for this change.
Existing code. Small spec (~5k lines formatted JSON). Average Resolution of ~1100ms.
With change. Average Resolution of ~250ms.
Existing code. Large spec (~141k lines formatted JSON). **NOTE: `allOf` plugin disabled for the below tests - only running `$ref` plugin.**
**????** I couldn't actually get this to complete in …

Add lookaside to `traverse` - Limits DFS revisit

---

src/execute/index.js
test.js
test/execute/main.js
test/oas3/execute/main.js

Adds support for operation and path-level `servers`.
Users will be able to provide path and operation `serverVariables` at request-time and they will be matched to the first `servers` definition that is found. Precedence is as follows: `operation > path > global`.
Users will still need to provide a `server` string found in a server definition that is matched to the operation, i.e. operations with `servers` in themselves or their path cannot try to use a global `server` definition.
Prerequisite for solving https://github.com/swagger-api/swagger-ui/issues/3820; companion to https://github.com/swagger-api/swagger-ui/pull/3972.
- I added some unit tests to cover the new functionality.
- I manually tested this within the UI.

OAS3: Path & Operation Servers

---

src/specmap/index.js
test/resolver.js

This PR replaces the existing traversal cache with a result cache. The traversal cache was prone to issues that were causing display bugs in UI/Editor.
Fixes https://github.com/swagger-api/swagger-editor/issues/1585. Fixes https://github.com/swagger-api/swagger-ui/issues/4000.
Follow-up to #1190. It's not as performant, but it is more accurate.
- I added a unit test that was previously failing.
- I linked the changes to Swagger-UI and observed that the display issues went away.

$ref resolution issues

---

src/specmap/index.js

cc @shockey - Lets try this again! 😆 
In #1190 - the lookaside actually prevented traversal of all properties of a reference - because we marked it as traversed and checked for this traversal before fully iterating the properties in the patch. This means that DFS was never fully complete for a `$ref` that we marked as traversed. This moves the check for previous traversal out of the loop and allows a complete traversal but prevents future traversals. Should be accurate as far as I can tell. 
I believe this was the root of "required" props not being parsed in swagger-api/swagger-ui#4000
Followup to #1201 and #1190. Again reduces resolution times to the #1190 range, but with greater accuracy. 
All tests pass. Tested with samples from swagger-api/swagger-editor#1585 & …

Re-implement lookaside for DFS during resolution

---

README.md

The link was pointing to master, where there is no `.min.js`. This PR fixes it, pointing the link to the `.min.js` in this branch (2.x).

Fixed broken link to swagger-client.min.js

---

.eslintrc
src/specmap/helpers.js
src/specmap/lib/all-of.js
src/specmap/lib/refs.js
test/specmap/all-of.js
test/specmap/refs.js

Fixes https://github.com/swagger-api/swagger-editor/issues/1343.

Ignore Swagger/OpenAPI freely-named key paths in $ref/allOf plugins

---

package.json
test/specmap/refs.js

Allows unit test execution in Windows. 
There is a [mocha bug](https://github.com/gotwarlost/istanbul/issues/677) that keeps tests from running in Windows. The change in the package.json is to resolve this.
Also - node-glob always provides a single slash path - ignoring the value of the path.sep. This replaces that value with the value of path.sep. This changes all forward slashes in these tests to be whatever path.sep is - which should allow execution and proper paths on any platform.
Fixes tests. Previously I ran tests with WSL (Windows Subsystem for Linux) - but got tired of dealing with it 😆 
All tests run / pass

fix(test): Fix test issues on Windows

---

src/execute/oas3/build-request.js
test/bugs/ui-4071.js

Addresses https://github.com/swagger-api/swagger-ui/issues/4071.

fix(oas3-encoding): encode form-urlencoded array values as comma-separated values by default

---

src/helpers.js
test/helpers.js

The previous code was looping through all known operations and update their __originalOperationId and operationId, after each one operation is added to the known list.
This is not only inefficient, but introduces a bug at the following line
```
obj.__originalOperationId = obj.__originalOperationId || operation.operationId
```
Where `operation` is the one that just got added and `obj` is the current operation in the loop.
This means for the following spec:
```
const spec = {spec: {
paths: {
'/foo': {
get: {
},
post: {
operationId: 'myId2'
}
},
}
}}
```
When operationId is not defined for the `get` operation, the __originalOperationId incorrectly gets set to 'myId2' when the post operation got added to the list.
Fixes #1221 
Added extra unit test to cover the above scenario

Remove the unnecessary loop of all operations when new one added

---

src/specmap/lib/refs.js

addresses https://github.com/swagger-api/swagger-ui/issues/4070

fix(resolver): accept yaml when fetching documents

---

src/execute/index.js
src/resolver.js
test/index.js

- Change the value of `credentials` according to the value of `http.withCredentials` as in the `README.md`.
- Change the value of `credentials` if `http.withCredentials` value is `true`.
- The issue is `credentials` is always 'same-origin' to fetch request.
- Cookies are not stored nor submitted across different origins.
- Fixes https://github.com/swagger-api/swagger-js/issues/1186
- Tested with two origins.
- UI running on `localhost:9292` sends requests to the server on `localhost:9293`.
- Video on testing the fix: [Testing swagger-js submitting cookies within two origins.](https://youtu.be/lXu1MR_Z730)
- Set cookies

Enable submitting cookies in CORS requests

---

package.json
src/specmap/index.js
src/specmap/lib/index.js
test/resolver.js
test/specmap/all-of.js
test/specmap/index.js

`$$ref` meta patches were being attached to the path referenced by a `$ref` as well as the destination, which was caused by the JSON Patch processor linking the $ref source and destination by referencing the same in-memory Object in both positions. This is bad for two reasons:
1. there's no need for information about the $ref source path, as it can be deduced by the data's back itself
2. it becomes impossible to consume $$refs as a marker of a $ref previously being in that position
This PR eliminates this issue by breaking the Object reference between the source and destination.
It also:
- moves to `fast-json-patch@1.2`
- refactors use of `op: '_get'` to `fast-json-patch`'s new `getValueByPointer` interface
- Unblocks https://github.com/swagger-api/swagger-editor/issues/1560.
- Paves the …

fix(resolver): don't attach $$ref meta patches to $ref origin locations

---

src/execute/oas3/style-serializer.js
test/oas3/execute/style-explode/query.js

fix deepObject serialization
This will fix the problem described in might fix  https://github.com/swagger-api/swagger-ui/issues/4064 
The deepObject style does not work as per described in teh spec
https://github.com/swagger-api/swagger-ui/issues/4064

fix deepObject serialization

---

README.md
src/index.js

- Removed `this.http.bind` statement
- Documentation is updated.
- The statement will not assign the `withCredentials` value of `http` function to the new `http` variable.
- Below is the test run in console.
```js
>  this.http
<- ƒ http(url) {
var request = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
if ((typeof url === 'undefined' ? 'undefined' : (0, _typeof3.default)(url)) === 'object') {
…
>  this.http.withCredentials
<- true
>  var bindedHttp = this.http.bind(this);
<- undefined
>  bindedHttp.withCredentials
<- undefined
```
- No method consumes `this.'any_property'` in the http (i.e.src/http.js) method. No use of binding.
- fixed https://github.com/swagger-api/swagger-js/issues/1186
- Tested with two origins.
- UI running on `localhost:9292` sends requests …

fix bind error to enable submitting cookies in CORS requests

---

src/specmap/helpers.js
src/specmap/lib/all-of.js
src/specmap/lib/refs.js
test/specmap/all-of.js
test/specmap/refs.js

Trying to fix https://github.com/swagger-api/swagger-ui/issues/4168

Add isFreelyNamed

---

package.json

In react native the dependancy fast-json-patch 1.2.2 causes problems. Update this dependancy to latest stable.
See issues:
https://github.com/swagger-api/swagger-js/issues/1239
https://github.com/Starcounter-Jack/JSON-Patch/issues/169
* Update version of fast-json-patch dependancy from 1.2.2 to 2.0.6 in package.json
Fixes #1239
Tested in affect react native application.
Tested using test script in swagger-js package
- [x ] Dependency changes (any modification to dependencies in `package.json`)
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the code style of this project.
- [x ] All new and existing tests passed.

Update fast-json-patch to 2.0.6

---

src/specmap/lib/refs.js
test/specmap/refs.js
test/subtree-resolver.js

This PR adds a new stopgap that prevents specmap from misclassifying local references within a remote document referenced by a whole-document pointer as indirect circular references.
Some notes I made while digging into this:
- The core issue appears to be that local references within the remote document are being flagged as an indirect cyclic reference, after we have crossed into that document with a top level reference (e.g. `./myDoc.json#`).
- The effect of this is that the $ref is left in place after the resolution cycle.
- Swagger-UI is throwing a "cannot resolve" error because the result of its first resolve cycle is fed in as the starting point for its second cycle, which is something we do to avoid needless duplicate resolutions. For debugging purposes, this message can be …

fix: don't classify remote document references as indirect circrefs

---

README.md

Based on discussion in https://github.com/swagger-api/swagger-js/issues/1262.

docs: add OpenAPI 3.0 guidance to tag interface

---

src/helpers.js
src/subtree-resolver/index.js
test/helpers.js
test/resolver.js
test/subtree-resolver.js

This PR: 
- normalizes subtree data _before_ attempting to resolve it, to solve the problem of path parameters outside of an operation's resolution discriminator being added to the operation in an unresolved form
- adds a top-level `$$normalized` marker to resolved definitions, in order to make the subtree resolver idempotent when its previous result is passed in as an input.
Fixes https://github.com/swagger-api/swagger-ui/issues/4327.

Normalize Swagger definitions before resolving a subtree

---

README.md
src/http.js
test/http.js

Analogous to Issue #1249, I would need the responseInterceptor to be able to modify the response asynchronously.
The idea is for the responseInterceptor to make another request and use the result in place of the previously received one. In particular I need this, because I need to handle redirect requests myself, because I need to receive cookies set on the redirect response. 
I've added a test to the test suite that performs a new request from the responseInterceptor (although from an error response, not a redirect).

Support asynchronous responseInterceptor

---

README.md
src/helpers.js
src/interfaces.js
test/helpers.js
test/index.js

This PR adds a top-level `v2OperationIdCompatibilityMode` option to Swagger-Client.
Fixes #1269!
I added a handful of unit tests that should cover the ID generator code, and the top-level option efficacy.

feature: operationId generator v2 compatibility mode

---

src/specmap/lib/all-of.js
test/specmap/all-of.js

_originally from @ponelat in #1264_
This adds a test, highlighting a bug.
With nested allOfs + $refs.
Example defintition fragment:
```yaml
definitions:
Alpha:
allOf:
- type: object
properties:
test:
$ref: '#/definitions/Bravo'
Bravo:
allOf: 
- type: object
properties:
two: 
type: string
```
Causes: ` TypeError: Cannot read property 'Alpha' of undefined`

add test for nested allOf + $ref

---

docs/MIGRATION_2_X.md

Fixes https://github.com/swagger-api/swagger-js/issues/1272.

docs(2to3-migration): add `Default Content-Type values` section

---

src/http.js
test/client.js

This PR modifies `http` to throw the original error from Fetch if the request itself failed to transport (as opposed to a non-OK status code, etc). This was necessary because #1261 caused this behavior to regress.
Fixes #1277.
A unit test has been added.

fix: http error handling regression

---

src/helpers.js
test/bugs/ui-4466.js

Addresses: 
- https://github.com/swagger-api/swagger-ui/issues/4466
- https://github.com/swagger-api/swagger-ui/issues/4467

fix: normalization regression

---

package.json

Updates a `0.x.y` dependency. Fixes #1304 (prototype pollution security issue).
Downstream projects are getting flagged by Snyk as impacted by the issue. 
Fixes #1304 
deep-extend 0.5.1 was a security fix release as per their changelog.

chore: update dependency to fix security issue

---

package.json
src/specmap/lib/index.js
test/resolver.js

When a $ref and a nested object value are present as members of an `allOf` array, the nested object value is extended onto the location the $ref points to, because inheritance between the grafted $ref value and the source location is not being broken.
This only shows up with nested inline object values, due to the fact that we have our own merging logic for shallow objects which _does_ take care of inheritance issues.
The solution: use a deep assign library to break inheritance with existing objects at any depth, before deeply extending the object.
Fixes https://github.com/swagger-api/swagger-ui/issues/4510.
I added two unit tests.

fix: $ref+allOf object inheritance-related allOf value bleed

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
.github/ISSUE_TEMPLATE/Support.md

MOAR issue templates

---

src/index.js
test/client.js
test/data/relative-host.swagger.yaml
test/data/relative-server.openapi.yaml

This allows OAS3 definitions to take advantage of relative server URLs.
Previous behavior:
- In a browser, the requests were made against the current page's host instead of the definition URL host
- In Node, the request failed
Swagger 2 analog test added as well, for completeness.

Relative URL construction based on remote definition URL

---

package.json
src/specmap/lib/index.js

Fixes https://github.com/swagger-api/swagger-js/issues/1315.

v3.8.2: use Node.js 4-compatible fork of `object-assign-deep`

---

src/execute/index.js
test/oas3/execute/main.js

According to: https://swagger.io/docs/specification/api-host-and-base-path/
If the server block doesn't exist, or is empty then it shall default to '/'
This seems to work for a missing servers block, but not for an empty list.
The old code attempted to access the first element in an array without checking if the list was empty.
This fix ensures that the array is not empty.
Fixes #1307 
I tested that the change fixes the following bug in swagger-ui https://github.com/swagger-api/swagger-ui/issues/4505
I used [this spec](https://gist.githubusercontent.com/dtkav/c49eeb14bcf5bd2370f74ba79cce9358/raw/21ac1f4a18813e7cde2da51596d1a91fd86233a1/petstore.yml) to trigger the failure.
I also added a new unit test to cover the change.
n/a

fix: handle empty servers list in oas3 spec when getting baseUrl (#1307)

---

src/execute/index.js
test/oas3/execute/style-explode/query.js

Supporting change for https://github.com/swagger-api/swagger-ui/pull/4563.

support string values for object type parameters

---

package.json
src/specmap/lib/refs.js
test/resolver.js

Supporting change for https://github.com/swagger-api/swagger-editor/issues/871.

fix: $ref value encoding and decoding

---

package.json
src/execute/oas3/build-request.js

Fixes https://github.com/swagger-api/swagger-js/issues/1326.
CC: https://github.com/strongloop/loopback-next/issues/1367, https://github.com/strongloop/loopback/issues/3894, https://github.com/strongloop/loopback-cli/issues/65.
This PR moves us to explicitly using `buffer` as our Buffer implementation, instead of relying on Webpack to prepare usage of Buffer globals.

fix + patch version: explicitly rely on buffer module

---

src/execute/oas3/parameter-builders.js
src/execute/swagger2/parameter-builders.js
test/execute/main.js
test/oas3/execute/main.js
test/swagger2/execute/build-request.js

This PR paves the way for a UI-based resolution of https://github.com/swagger-api/swagger-ui/issues/4223.
TLDR: `allowEmptyValue` is different from `required`.
Previously, there was no way to express to Swagger Client that an `allowEmptyValue` parameter should not be present. 
Given:
```yaml
parameters:
- name: myParam
in: query
allowEmptyValue: true
```
All of these execute `parameters` values would result in `/?myParam=`:
```js
{}
```
```js
{
myParam: undefined
}
```
```js
{
myParam: ""
}
```
Given:
```yaml
parameters:
- name: myParam
in: query
allowEmptyValue: true
```
....these execute `parameters` values result in the following:
```js
{} 
```
yields `/`.
```js
{
myParam: undefined
}
```
yields `/`.
```js
{
myParam: ""
}
```
yields `/?myParam=`.
_@webron_
This is, strictly speaking, a …

Allow omission of `allowEmptyValue: true` parameters

---

release/.release-it.json

This change allows the `@latest` npm tag to be updated when releases occur.

build(automated-release): remove custom npm config

---

package.json
src/specmap/index.js
src/specmap/lib/index.js

⚠️ This PR reverts f8fccb4 aka #1203.
The original PR introduced a browser-specific issue (https://github.com/swagger-api/swagger-ui/issues/4748) in the resolver.
The exact mechanism causing the failure was not identified, but my manual testing confirmed that specmap patches were not being applied at all within IE11.
According to our `size-check` script, this change has a negligible (`<1K`) impact on our bundle size. I assume this is because we never realized the ~22K savings from dropping the regenerator, because we still had the `transform-runtime` plugin in our Babel config:
https://github.com/swagger-api/swagger-js/blob/9c5e991b8e0b26d7b18216be7c02bc968494d103/.babelrc#L27
I've manually tested the changes.
Forthcoming cross-browser tests in Swagger UI would have caught this prior to …

revert: "remove babel-runtime runtime dependency"

---

src/specmap/lib/refs.js
test/resolver.js

This PR modifies the `$ref` plugin to shield it from generating `replace` patches that point to paths not currently in Specmap's state.
This prevents an edge case caused by state slippage due to interactions between plugins touching the same path in one patch-generation pass, though this is a narrow fix for a broad problem. A more comprehensive fix would require a major overhaul to Specmap.
This PR fixes an issue that was reported privately (id ~`SWOS-22`~ `SWOS-34`).
Unit tests were added to cover the case in question, and the resulting Swagger Client build was tested in integration with Swagger UI.

fix(resolver): drop patches that reference nonexistent paths

---

src/execute/oas3/parameter-builders.js
test/oas3/execute/style-explode/path.js

URL encode parameters for OpenApiSpec 3
Fixes this issue in swagger-ui https://github.com/swagger-api/swagger-ui/issues/4025
I guess it was disabled by accident in https://github.com/swagger-api/swagger-js/pull/1181 which was about allowing to skip url encode for query params if `Paramter.allowReserved` is set to true. But [specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md) says clearly: 
`
Determines whether the parameter value SHOULD allow reserved characters, as defined by RFC3986 :/?#[]@!$&'()*+,;= to be included without percent-encoding. This property only applies to parameters with an in value of query. The default value is false.
`. So it should be applied only to query params and path parameters should use encoding all the time
I'm not …

URL encode parameters for OpenApiSpec 3

---

src/execute/swagger2/build-request.js
test/index-authorizations.js

The previously supported `x-tokenName` can be used in order to select another field from the token JSON as bearer token.
As noted in [`swagger-ui`#4084](https://github.com/swagger-api/swagger-ui/issues/4084), v2 supported the `x-tokenName` spec extension to allow for tokens other than `access_token` to be used for "Try it Out" requests with OAuth2 security. Most notably, this allows for the selection of the `id_token` for service authorization. This PR restores that functionality for swagger2 specs.
Added a test case that uses `id_token` for authentication.

Restore swagger2 support for x-tokenName extension in OAuth2 security

---

src/execute/oas3/style-serializer.js
test/oas3/execute/style-serializer.js

Low value unicode characters were not encoded properly. For example, 'LINE FEED (LF)' (U+000A) was encoded as '%A' instead of '%0A' which cannot be decoded properly.
Low value unicode characters were not encoded properly. For example, 'LINE FEED (LF)' (U+000A) was encoded as '%A' instead of '%0A' which cannot be decoded properly.
I tested the output directly in the browser

Fix lack of leading zero on low unicode values

---

release/get-changelog.sh

I've been using a new style for release notes, this reflects that.
The new changelog generator now sorts items as we like them, and pulls in stray commits that may not be to the Angular convention's liking, but we may still want present.

housekeeping: make changelog generator more flexible

---

release/.release-it.json

`test:webpack` no longer exists, it was folded into `test:unit` in #1438

housekeeping: remove `test:webpack`from release configuration

---

examples/quick.js
package-lock.json
package.json
src/http.js
src/specmap/lib/refs.js
test/oas3/execute/authorization.js
test/oas3/execute/main.js
test/oas3/execute/style-explode/cookie.js
test/oas3/execute/style-explode/header.js
test/oas3/execute/style-explode/path.js
test/oas3/execute/style-explode/query.js
test/resolver.js
test/resolver/index.js
webpack/_config-builder.js

coordinated with:
* https://github.com/swagger-api/swagger-ui/pull/5511
* https://github.com/swagger-api/swagger-editor/pull/2025

housekeeping: `@kyleshockey/js-yaml` -> `js-yaml`

---

src/specmap/lib/refs.js
test/bugs/ui-4924.js

...in RequestBody/Response Media Type Example values
fixes https://github.com/swagger-api/swagger-ui/issues/4924

fix: non-standard resolution behavior

---

src/execute/oas3/build-request.js
test/oas3/execute/authorization.js

Enables using `x-tokenName` in OpenAPI 3.0 OAuth security schemes in order to select a different field from the token JSON for use as the bearer token.
Fixes swagger-api/swagger-ui#4084.
I've added a test case for it that provides both the default `access_token` and a non-default `id_token`, and confirms the latter is used.
- Something about my environment doesn't play well with most of the tests, causing failures via timeout, but the new and all existing `test/oas3/execute` tests pass.

Support x-tokenName extension in OpenAPI 3.0 specs

---

src/execute/oas3/parameter-builders.js
test/oas3/execute/style-explode/query.js

URL encode the query parameter name which can contain restricted characters like square brackets: []
JSON:API suggests using query parameters to specify pagination controls like this: `page[offset]=0`. When using OAS 3.0 the square brackets in this parameter name are not being URL encoded, which causes Try It Out attempts that specify these parameters to fail. This was not a problem with Swagger 2.0 files. The URL encoding did happen there.
This has already been reported in swagger-api/swagger-ui#5304
I have written a unit test for this change which is included in the PR.
I have not been able to test this fully integrated into Swagger UI however.  I'm just not clear on how to do that honestly.  Looks like I'm not the only one: #1461. I would be happy to do that testing if someone can …

URL encode the query parameter name

---

src/index.js
test/webpack-bundle/index.js

Exposing **baseUrl** method
Making **baseUrl** method available for consumption.
We have a requirement where our users desire route URLs on **swagger-ui** to have a copy-to-clipboard functionality. To do so, we need the output of the **baseUrl** method to be appended with a specific path sub URL to obtain the absolute URL for a route. Currently, the **baseUrl** method is not exposed for consumption. 
We are aware of the **buildRequest** method. Unfortunately, it does not work without the mandatory route parameters. However, the functionality that we are looking for just requires fetching the route path without appending the parameter values. 
The baseUrl method has been tested for in the existing test cases. As part of this change, the method has been exposed. Hence, it is not expected to …

making baseUrl method available for consumption

---

src/execute/oas3/build-request.js
src/execute/swagger2/build-request.js
test/oas3/execute/authorization.js
test/swagger2/execute/apply-securities.js

Don't cast non-string passwords to string (e.g. undefined to "undefined").
I'm not sure if `value.password instanceof String` is needed or if a test for plain strings would be sufficient. Or should it explicitly test for `undefined`? Because people expect whatever they pass to be converted to string implicitly, except the blank password case?
Should the username also be checked?
Empty passwords for basic HTTP authorization is a valid use case (see https://github.com/swagger-api/swagger-ui/issues/5410) and I opened a PR to allow this in the frontend (https://github.com/swagger-api/swagger-ui/pull/5812), but it turned out that the swagger-client casts the undefined `password` to a string, leading to an incorrect base64-encoded password.
- `"root:undefined"` → `"cm9vdDp1bmRlZmluZWQ="` ❌
- …

Basic auth: Support empty passwords

---

package-lock.json

I don't like to scuttle lockfiles, but there were >24,000 vulnerabilities coming from `kind-of` via  https://npmjs.com/advisories/1490 that `npm audit fix` and surgical `npm update kind-of --depth n` runs weren't resolving 🤷‍♂

housekeeping: regenerate `package-lock.json`

---

docs/usage/http-client.md

Fixes typos in documentation code samples: `s/clinet/client`

Fix typos in documentation

---

package-lock.json
package.json
src/http.js
test/http.js
test/jest.setup.js

I needed to update very old cross-fetch@0.0.8 to cross-fetch@3.0.4
which uses 2.x branch of node-fetch instead of 1.x branch.
node-fetch@1.x is no longer compatible with fetch API in browsers
and is incompatible with the fetch specification.
Ref #1508
Header serialization issues. More in #1508
Existing tests have been amended to compenseta for fetch API spec changes.

fix: amend header serialization algorithm

---

test/resolver/index.js

Explicit return was returning a Promise which caused jest to think
that we rely on describe block resolving the Promise before running
tests.
Ref #1529
Warnings inside tests
By running tests
```sh
(node:4106) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS  test/resolver/index.js
PASS  test/specmap/refs.js
PASS  test/client.js
PASS  test/specmap/index.js
PASS  test/index.js
(node:4106) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ok' of undefined
(node:4106) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled …
```

test(resolver): remove explicit return from generated describe block

---

docs/usage/http-client.md
docs/usage/openapi-definition-resolver.md
package-lock.json
package.json
src/execute/oas3/build-request.js
src/http.js
test/data/sample-multipart-oas2.js
test/data/sample-multipart-oas3.js
test/execute/main.js
test/http-multipart.js
test/http.js
test/resolver/index.js
webpack.common.js

Multipart/form-data support for
- OAS 2.0
- OAS 3.0
- includes `file` and `files`
Also fixes: cross browser and node support
- `@timlai/isomorphic-form-data` single replacement for `isomorphic-form-data`, `form-data`, and `formdata-node`. However, under the hood, `@timlai/isomorphic-form-data` uses `formdata-node`, which replaces `form-data`, to get FormData methods parity with browser
housekeeping: update webpack config to support webpack4
- use `rules` instead of `loaders`
Fixes #1526 
Fixes #1505 
Fixes #1480
Fixes #1470
supersedes #1485
New tests created in `test/http-multipart.js`
- includes skipped test to live local node/express server
Tested on Node v13.9

fix: buildRequest of multipart/formdata with array entries

---

package-lock.json

cleanup package-lock to reflect actual current dependency tree
In earlier commit, it appears that package-lock still contained references to dependencies that are no longer used in the project. This included dependencies installed as part of debug/trial/testing. 
Hopefully this will help production release build
Does not appear to have impact on local build or test.

housekeeping: cleanup package-lock

---

package-lock.json
package.json

Problem was resolved by updating nock library to newest versions
that no longer uses node deprecated API.
When running tests, deprecation warning DEP0066 was triggering warning.
https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_prototype_headers_outgoingmessage_prototype_headernames

test(resolver): fix node deprecation warning DEP0066

---

package-lock.json
package.json
src/http.js
src/internal/form-data-monkey-patch.js
test/execute/main.js
test/http-multipart.js

Replace `formdata-node` with an internal patch of `form-data`. Update tests to reflect dependency change.
commit  b35d36b introduced a dependency change from `form-data` to `formdata-node`. The reason was that `form-data` is missing matching methods for FormData. However, `formdata-node` also required Node 10, which is technically a breaking semver change for `swagger-client`, but not noted as a breaking semver change in the release v3.10.3.
We are choosing to maintain `swagger-client` in a non-breaking semver state. As a result, we are applying an internal patch to `form-data` and removing `formdata-node`.
Note: Node 8 has been EOL for some time now, and remains technically unsupported by `swagger-client`.
Existing tests updated to reflect change between `formdata-node` and `form-data` + …

Form data monkey patch

---

src/http.js
test/data/sample-multipart-oas2.js
test/http-multipart.js

Fix OAS2 collectionFormat handling for non-multipart cases
```
collectionFormat: csv
collectionFormat: tsv
collectionFormat: ssv
collectionFormat: pipes
```
Previous OAS2 multipart fixes did not cover non-multi cases.

fix: oas2 collectionFormat when not 'multi'

---

src/execute/oas3/build-request.js
src/execute/oas3/parameter-builders.js
src/http.js
test/bugs/ui-4071.js
test/data/sample-multipart-oas3.js
test/http-multipart.js
test/http.js
test/oas3/execute/style-explode/query.js

Serialize value with respect to `Encoding Object` when the content-type of the request body is `application/x-www-form-urlencoded`.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#encoding-object
Also, OpenAPI v3.1 has a specification to serialize similarly when content-type is `multipart/form-data`, so it was implemented at the same time.
https://github.com/OAI/OpenAPI-Specification/blob/v3.1.0-dev/versions/3.1.0.md#encodingObject
In addition, a bug that prevented sending an array of files was also fixed.
Currently, swagger-client does not work according to the serialization specification of the request body of the form. This pull request is modified to respect the request body serialization settings.
In OpenAPI v3.1, the serialization settings will be …

Encode form data according to Encoding Object

---

test/http.js

Replace `new Buffer()` with `Buffer.from()`
ref: https://nodejs.org/fa/docs/guides/buffer-constructor-deprecation/
PR #1500 introduced new tests that used `new Buffer()`, which was not captured in the review.
> DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead 
deprecation warnings no longer present in test result

fix: Buffer deprecation warning

---

test/oas3/execute/authorization.js

test(authorization): correct OAS3 fixtures

---

src/execute/oas3/build-request.js
test/oas3/execute/authorization.js

As per RFC7235 auth scheme is case insensitive.
2.1. Challenge and Response
HTTP provides a simple challenge-response authentication framework
that can be used by a server to challenge a client request and by a
client to provide authentication information. It uses a case-
insensitive token as a means to identify the authentication scheme,
followed by additional information necessary for achieving.
https://tools.ietf.org/html/rfc7235#section-2.1
Refs #1531, #1473
Refs https://github.com/OAI/OpenAPI-Specification/issues/1876
Refs https://github.com/swagger-api/swagger-ui/issues/5965

fix(scheme): make scheme comparison case insensitive

---

package-lock.json
package.json
src/specmap/lib/index.js

Function was replaced by standard lodash.cloneDeep function.
As we used custom build of object-assign-deep of unknown version which was exclusively use for deep cloning of recursive structures, it was replaced by standard lodash.cloneDeep function.
Remove dep that we don't have control over.

refactor: replace custom build of object-assign-deep

---

config/jest/jest.unit.coverage.config.js
package.json

In order to fail the CI if somebody introduces code without tests, we'll use jest coverage in order to achieve that.

ci(GA): runs code coverage with thresholds checks

---

release/.release-it.json

release-it was generating commit message not compliant with conventional commit specification. This PR fixes it.
Will be tested in next release

build(release-it): configure proper release commit msg

---

.babelrc
package-lock.json
package.json
src/specmap/lib/index.js
test/build-artifacts/es.js
test/jest.setup.js

We've been using `@babel/runtime-corejs2` as production dependency because of one single check - to tell if a function is a generator function. Now that we target `node >=8` regenerator-runtime is no longer needed except for other environments where ES5 compliant code with generator is required. This case will be handled implicitly by `@babel/plugin-transform-runtime` plugin.

build: remove regenerator-runtime from production deps

---

.github/workflows/nodejs.yml

We're building our node artifacts agains node >=8. We have to make sure that the artifacts are executable on node 8.

ci(GA): add node 8.x artifacts tests

---

package.json

According to this thread https://github.com/webpack/webpack/issues/4674
it's not recommended  to use browser field for isomorphic libraries.
Discussion about browser field:  https://github.com/webpack/webpack/issues/4674
Browser field specification:  https://github.com/defunctzombie/package-browser-field-spec
Refs #1542

build(package): remove browser field

---

.babelrc
package-lock.json
package.json

Use property now utilize @babel/plugin-transform-runtime and use
@babel/runtime-corejs2 as a runtime dependency.
Decrease size of build fragments.
Tested with swagger-ui.

build(babel): decrease size of ES5 build fragment

---

docs/usage/installation.md

`require` directives in node.js require a closing semicolon, otherwise a strange error message gets shown:
```
}) ()
^
TypeError: require(...)(...) is not a function
```
/
/
Manually
/

installation.md - semicolon missing

---

src/execute/oas3/build-request.js
test/oas3/execute/authorization.js

Securities are to be formatted the same way as oauth2, since OIDC is
just a layer on top of oauth2.

feat(build-request): Add support for openIdConnect

---

.github/dependabot.yml

As release-it package is no longer used, we'll good
to remove these ignores.
Refs #2049

ci(dependabot): remove ignores for release-it

---

package-lock.json
package.json

This minor version bump is still uses node-fetch@2.6.1
under the hood which is in sync with our node-fetch
explicit dependency.

chore(deps): update cross-fetch to v3.1.4

---

.github/workflows/release.yml

Release workflow have been run even if "Node.js CI" workflow fails. This PR fixes this by running a release workflow only on successful completion of "Node.js CI" (not just completion which can mean success or failure).

chore(release): trigger release workflow only on success

---

docs/usage/tags-interface.md
src/index.js
test/index.js

fix(constructor): accept skipNormalization option

---

src/execute/oas3/parameter-builders.js
src/http/index.js
src/interfaces.js

I removed and replaced `lodash.pick` with object destructuring 
part of #2187 
executed test

removed lodash.pick

---

src/execute/index.js
src/execute/oas3/build-request.js
src/execute/swagger2/build-request.js
src/index.js

I removed and replaced `lodash/isArray` with native Array.isArray
Same for assign
part of #2187 
executed test

Remove lodash isArray + assign

---

.github/workflows/nodejs.yml
package-lock.json
package.json

Dependabot alerts will replace the script.
Closes #2325

chore(security): discontinue using npm audit script

---

docs/usage/http-client-for-oas-operations.md
docs/usage/tags-interface.md
package-lock.json
package.json
src/execute/index.js
test/execute/main.js
test/interfaces.js

- support was added to HTTP Client for OAS operations
- support was added to Tags Interface
Older versions of swagger-client can use request
interceptors to inject abort signal into requests.
Refs #2349
With automated tests and manually.

feat: add support aborting requests in tags interface

---

.npmrc
package-lock.json
package.json
test/build-artifacts/umd.js

As our build target progressed, babel no longer polyfills
Promise global object. This has certain effect on a particular
test that srated failing. Test has been removed to reflect
our new reality.
Refs #1640
Closes #2618
Closes #2616
By manually inspecting the browser UMD bundle.

chore(deps-dev): update @babel/* deps to v7.18.10

---

.github/workflows/nodejs.yml
.github/workflows/release.yml

Jest no longer runs on Node.js 12. It needs to run tests on Node.js 14 now. We're still test build fragments in Node.js 12.4 though.

ci(ga): drop Node.js v12 from pipeline

---

.github/dependabot.yml
.github/workflows/release.yml

Dependabot was configured to update GitHub Actions automatically
Refs #2738

ci(release): update semantic-release-action to v3.2.0

---

src/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/visitors/dereference.js
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/example-object/index.js
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/reference-object/__fixtures__/direct-external-circular/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/reference-object/__fixtures__/direct-external-circular/ex.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/reference-object/__fixtures__/direct-internal-circular/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/reference-object/__fixtures__/indirect-external-circular/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/reference-object/__fixtures__/indirect-internal-circular/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/reference-object/__fixtures__/invalid-pointer/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/reference-object/__fixtures__/max-depth/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/reference-object/__fixtures__/unresolvable-reference/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/reference-object/index.js

This change is specific to OpenAPI 3.1.0 resolution strategy. Errors are now collected, instead of
Refs #2802

feat(resolver): collect errors in ReferenceElement visitor hook

---

src/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/errors/index.js
src/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/visitors/dereference.js
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/__fixtures__/$anchor-not-found/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/__fixtures__/$id-unresolvable/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/__fixtures__/$ref-url-unresolvable/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/__fixtures__/$ref-urn-unresolvable/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/__fixtures__/direct-external-circular/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/__fixtures__/direct-internal-circular/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/__fixtures__/indirect-external-circular/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/__fixtures__/indirect-internal-circular/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/__fixtures__/indirect-internal-circular/root.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/__fixtures__/infinite-recursion/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/__fixtures__/invalid-pointer/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/__fixtures__/max-depth/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/__fixtures__/unresolvable-reference/dereferenced.json
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/index.js

This change is specific to OpenAPI 3.1.0 resolution strategy. Errors are now collected, instead of
Refs #2806

feat(resolver): collect errors in SchemaElement visitor hook

---

src/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/index.js
src/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/utils/compose.js
src/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/visitors/all-of.js
test/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/all-of.js

This change is specific to OpenAPI 3.1.0 resolution strategy. Errors are now collected, instead of
Refs #2808

feat(resolver): collect errors in AllOfVisitor hooks

---

src/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/index.js
src/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/visitors/properties.js
test/resolver/strategies/openapi-3-1/__fixtures__/model-property-macro-error.json
test/resolver/strategies/openapi-3-1/__snapshots__/index.js.snap
test/resolver/strategies/openapi-3-1/index.js

This change is specific to OpenAPI 3.1.0 resolution strategy. Errors are now collected, instead of
Refs #2810

feat(resolver): collect errors in ModelPropertyMacro visitor hooks

---

src/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/index.js
src/helpers/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/visitors/parameters.js
src/specmap/lib/parameters.js
test/resolver/strategies/openapi-3-1/__snapshots__/index.js.snap
test/resolver/strategies/openapi-3-1/index.js

This change in specific to OpenAPI 3.1.0 resolution strategy. Errors are now collected, instead of
Refs #2812

feat(resolver): collect errors in ParameterMacroVisitor visitor hooks

---

config/webpack/browser.config.babel.js
package-lock.json
package.json

feat(build): limit the size of UMD build fragment as much as possible

---

package-lock.json
package.json
scripts/overrides.js

Without this fix `npm ci` script in newer npm versions 
has problem consolidating the dependency tree.

fix(build): fix bundling of overridden ApiDOM deps

---

src/index.js
src/resolver/index.js
src/subtree-resolver/index.js

Resolve makers are functions that pre-configure
resolve and resolveSubTree functions with default
options.

feat(resolver): expose resolve makers

---

.github/workflows/release.yml
.releaserc

The CICD pipeline was disabled during alpha/beta phases of 3.19.0 release. This change re-enables it.

ci(release): re-enable automatic CICD pipeline

---

config/jest/jest.unit.coverage.config.js
package-lock.json
package.json
src/helpers/fetch-polyfill.browser.js
src/helpers/fetch-polyfill.node.js
src/helpers/fetch-ponyfill-node-fetch.node.js
src/helpers/fetch-ponyfill-undici.node.js
src/helpers/fetch-ponyfill.browser.js
src/http/index.js
test/execute/main.js
test/http/http-multipart.js
test/http/index.js
test/jest.setup.js
test/oas3/execute/build-request.js

Depending on Node.js version, FormData, File and Blob are used from following fetch implementation:
- `>=12.20.0 <16.8` - [node-fetch@3](https://www.npmjs.com/package/node-fetch)
- `>=16.8 <18` - [undici](https://www.npmjs.com/package/undici) 
- `>=18` - [native Node.js fetch](https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch)
Refs #3137

feat: use FormData, File and Blob from fetch implementation

---

config/jest/jest.unit.coverage.config.js
package-lock.json
package.json
src/helpers/abortcontroller-polyfill.browser.js
src/helpers/abortcontroller-polyfill.node.js
src/helpers/abortcontroller-ponyfill.browser.js
src/helpers/abortcontroller-ponyfill.node.js
src/resolver/apidom/reference/resolve/resolvers/http-swagger-client/index.js
test/execute/main.js
test/interfaces.js
test/jest.setup.js

For browser env, the native `AbortController` and `AbortSignal` will be used. For Node.js not supporting `AbortController` and `AbortSignal`, `node-abort-controller` npm package is used to provide the functionality.

fix: use AbortController in backward compatible way for Node.js >=12.20.0

---

src/helpers/index.js
src/helpers/is-http-url.js
src/index.js

This change is specific to OpenAPI 3.x.y definitions.
Refs #3143
---
Supersedes https://github.com/swagger-api/swagger-js/pull/3218

fix: create default OpenAPI.servers fields if omitted

---

src/execute/index.js
src/index.js

This change is specific to OpenAPI 3.x.y definitions.
Refs #3143

fix: create spec compliant default OpenAPI.servers fields if omitted

---

docs/usage/http-client-for-oas-operations.md

docs(http-client-for-oas-operation): document server and contextUrl options

---

src/constants.js
src/execute/index.js
src/index.js

This change is specific to OpenAPI 2.0 and OpenAPI 3.0.x.
Refs #2967

fix(execute): handle Server Objects overrides for OpenAPI 2.0/3.0.x

---

src/execute/oas3/parameter-builders.js
test/execute/openapi-3-1.js

Refs https://github.com/swagger-api/swagger-ui/issues/5176
Fixes the issue for when no value is selected, sending an empty string in an array after selecting the '--' option is a separate issue in Swagger UI.

fix(execute): empty field added to multi-value parameters

---

README.md
package-lock.json
package.json
src/helpers/fetch-polyfill.node.js
src/helpers/fetch-ponyfill-undici.node.js
test/jest.setup.js

Refs #3382
Refs https://github.com/nodejs/undici/issues/2521
Swagger-client Fetch API support in Node.js environment has moved from this:
```
>=12.20.0 <16.8 - [node-fetch@3](https://www.npmjs.com/package/node-fetch)
>=16.8 <18 - [undici](https://www.npmjs.com/package/undici)
>=18 - [native Node.js fetch](https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch)
```
to the following
```
>=12.20.0 <18 - [node-fetch@3](https://www.npmjs.com/package/node-fetch)
>=18 - [native Node.js fetch](https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch)
```

fix(security): fix proxy-Authorization header security issue

---

src/execute/oas3/parameter-builders.js
test/oas3/execute/main.js

Refs https://github.com/swagger-api/swagger-ui/issues/9550

fix(execute): skip undefined values serialization

---

src/execute/swagger2/parameter-builders.js
test/execute/main.js

fix(execute): skip undefined parameters in body and path request builders for OpenAPI 2.0

---

src/execute/oas3/style-serializer.js
src/http/index.js
test/oas3/execute/main.js

Refs https://github.com/swagger-api/swagger-ui/issues/9755
From the test example, when encoding these parameters:
```
query: {
a: {
b: {
c: 'd',
},
},
},
pathPartial: {
foo: {
bar: { baz: 'qux' },
},
a: {
b: {
c: 'd',
},
},
}
```
we will now get the following URL:
```
/foo=%7B%22bar%22%3A%7B%22baz%22%3A%22qux%22%7D%7D,a=%7B%22b%22%3A%7B%22c%22%3A%22d%22%7D%7D?a=%7B%22b%22%3A%7B%22c%22%3A%22d%22%7D%7D
```
which will decode to: 
```
/foo={"bar":{"baz":"qux"}},a={"b":{"c":"d"}}?a={"b":{"c":"d"}}
```
The cURL result for the 2.0 specification is:
```
curl -X 'GET' \
'https://petstore.swagger.io/v2/pet/findByStatus/%7B%22test%22%3A%20%7B%22test2%22%3A%20%22test3%22%20%7D%20%7D?queryParam=%7B%22test%22%3A%20%7B%22test2%22%3A%20%22test3%22%20%7D%20%7D' \
-H 'accept: application/xml' \
-H …
```

fix(execute): fix encoding of complex nested type values in OpenAPI 3.x request builders

---

src/execute/oas3/parameter-builders.js
src/execute/oas3/style-serializer.js
test/oas3/execute/style-serializer.js

fix(execute): refactor encodeDisallowedCharacters function

---

src/execute/oas3/content-serializer.js
test/oas3/execute/main.js

Refs https://github.com/swagger-api/swagger-ui/issues/9521
The URL for this example:
should now be encoded as:
```
http://localhost:3200/endpoint?param=%5B%7B%22a%22%3A%7B%22c%22%3A%22string%22%7D%2C%22b%22%3A0%7D%5D
```
which should decode to:
```
http://localhost:3200/endpoint?param=[{"a":{"c":"string"},"b":0}]
```

fix(execute): parse stringified objects nested in arrays

---

src/http/index.js
test/oas3/execute/main.js

Refs https://github.com/swagger-api/swagger-ui/issues/7734
This example from the test:
```js
requestBody: {
a: {
b: 'c',
c: ['d', 'e'],
d: {
e: 'f',
},
},
},
```
will return: 
```
a%5Bb%5D=c&a%5Bc%5D=%5B%22d%22%2C%22e%22%5D&a%5Bd%5D=%7B%22e%22%3A%22f%22%7D
```
which should decode to:
```
a[b]=c&a[c]=["d","e"]&a[d]={"e":"f"}
```
As established for previous issues, we're not encoding nested objects/arrays, as the behaviour for that is undefined.

fix(execute): parse stringified objects

---

src/http/index.js
test/oas3/execute/main.js

Refs https://github.com/swagger-api/swagger-ui/issues/7810
With these changes we should now parse the string and then iterate through it only if it's actually an object.
The issue is that we are sending a stringified object and then iterating through it as if it were just an object. It happened even if I updated the examples in the specification provided in the issue, which seemed wronged to me,  to:
```yaml
examples:
authorization_code grant type:
description: authorization_code grant type
value:
grant_type: authorization_code
code: xxxxxxxxxx
client_id: xxxxxxxxxx
client_credentials grant type:
description: client_credentials grant type
value: 
grant_type: client_credentials
client_id: xxxxxxxxxx
client_secret: xxxxxxxxxx
refresh_token grant type:
description: refresh_token grant type …
```

fix(execute): fix encoding for stringified request body

---

src/execute/index.js
src/execute/oas3/build-request.js
src/http/index.js
src/http/serializers/request/file.js
src/http/serializers/request/format.js
src/http/serializers/request/index.js
src/http/serializers/response/index.js
src/index.js
test/http/index.js

Refs #3481
1. Moved request and response serializing/encoding into separate files 
2. Moved the logic introduced by https://github.com/swagger-api/swagger-js/pull/3476 and https://github.com/swagger-api/swagger-js/pull/3474 to request builder

refactor(http): refactor http client

---

.eslintrc
config/webpack/browser.config.babel.js
package-lock.json
package.json
src/execute/index.js
src/execute/oas3/parameter-builders.js
src/execute/swagger2/parameter-builders.js

fix(security): replace regular expressions in path builders

---

src/execute/index.js

fix(security): fix polynomial regular expression

---

src/execute/index.js
src/execute/oas3/parameter-builders.js
src/execute/swagger2/parameter-builders.js
test/execute/main.js

fix(execute): resolve multiple path parameters with the same name in path templates

---

docs/usage/http-client-for-oas-operations.md
package-lock.json
package.json
src/execute/index.js
test/execute/server-variable-encoder.js

This will allow Saas and On-Premise usecase to be handled correctly.
Encoding can be turned on again by providing serverVariableEncoder option.
Refs #3656
---
**WARNING**: needs testing with SwaggerUI before merging.

fix(execute): do not encode server variables by default

---

package-lock.json
package.json

Fix was provided by updating cookie to v0.7.2.
Refs CVE-2024-47764
Refs GHSA-pxg6-pf52-xh8x

fix(security): fix unsafe cookie serialization

---

README.md
package-lock.json
package.json

Swagger Client uses [Scarf](https://scarf.sh/) to collect [anonymized installation analytics](https://github.com/scarf-sh/scarf-js?tab=readme-ov-file#as-a-user-of-a-package-using-scarf-js-what-information-does-scarf-js-send-about-me). These analytics help support the maintainers of this library and ONLY run during installation. To [opt out](https://github.com/scarf-sh/scarf-js?tab=readme-ov-file#as-a-user-of-a-package-using-scarf-js-how-can-i-opt-out-of-analytics), you can set the `scafeSettings.enabled` field to `false` in your project's `package.json`:
```
// package.json
{
// ...
"scarfSettings": {
"enabled": false
}
// ...
}
```
Alternatively, you can set the environment variable `SCARF_ANALYTICS` to `false` as part of the environment that installs your npm packages, e.g., …

feat(analytics): use Scarf.js to provide anonymized installation analytics

---

src/execute/oas3/style-serializer.js
src/http/serializers/request/index.js
test/oas3/execute/main.js

Refs https://github.com/swagger-api/swagger-ui/issues/10226
Fixes the issue with `null` and `undefined` values causing errors due to trying to check their length.

fix(execute): fix encoding of object properties with null value

---

package-lock.json
package.json

Refs https://github.com/OAI/OpenAPI-Specification/pull/4244 
Refs https://github.com/swaggerexpert/openapi-path-templating/releases/tag/v2.0.0
This PR aligns processing of [Path templating](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.1.md#path-templating), with now official [OpenAPI ABNF grammar](https://github.com/OAI/OpenAPI-Specification/pull/4244).
The only noticeable effect for OpenAPI description authors is more relax rules around what is allowed as valid characters inside the brackets `{}`.

fix(execute): align Path Templates processing with OpenAPI spec

---

src/index.js
src/resolver/strategies/openapi-3-1-apidom/resolve.js
test/index.js
test/resolver/strategies/generic/index.js
test/resolver/strategies/openapi-3-1-apidom/index.js

fix(resolver): align resolver strategies behavior on invalid path discriminator

---

src/execute/index.js
src/execute/oas3/parameter-builders.js
src/helpers/cookie-value-encoder.js
test/oas3/execute/authorization.js
test/oas3/execute/main.js
test/oas3/execute/style-explode/cookie.js

This is part of aligning with OpenAPI 3.0.4 clarifications.
Specifically this PR is aligning implementations around cookies with https://spec.openapis.org/oas/v3.0.4.html#appendix-d-serializing-headers-and-cookies.
`swagger-client` will now product valid cookies, which can be processed by [RFC 6265](https://tools.ietf.org/html/rfc6265) parser, `cookie-value` is percent decoded and can be further processed by [RFC 6570](https://www.rfc-editor.org/rfc/rfc6570) implementation.

fix(execute): serialize req.cookies into valid cookie-string

---

src/resolver/strategies/generic/normalize.js

This PR fixes acessing properties of empty parameters during normalization, e.g.:
```yaml
openapi: 3.0.4
paths:
/test:
parameters:
- 
get:
parameters:
- 
```

fix(resolver): avoid accessing properties of undefined or null parameters
