src/js/swagger-compat.js

Fixed check for absolute URL

---

lib/swagger-client.js
src/js/swagger-a.js
src/js/swagger-compat.js
test/compat/request.js

Looks like a typo in ```swaggerRequstHeaders```.

Renamed swaggerRequstHeaders to swaggerRequestHeaders

---

test/mock.js

Fixes the tests that are failing as a result of e2c0bb2.

Follow up for e2c0bb2 to fix failing tests

---

test/client.js

Add test to show we handle empty tags properly

---

lib/types/model.js
test/models.js

Modified source and created test to make use of "title" in models when avaialble

Use title in models when available per swagger-ui #1104

---

README.md

Updated browser example in README to be a working example

---

lib/types/operation.js
test/operation.js

fixes swagger-api/swagger-ui#1166

default "Accept" header to one found in #produces

---

README.md
browser/index.html

I have update the documentation and sample index.html to show how to use the SwaggerClient as the current documentation seems to be wrong

Fix documentation and sample code for browser usage

---

lib/types/operation.js
test/compat/defaultCallbacks.js

Add back the default error/success callbacks

---

lib/helpers.js

This code is causing memory leak in long running app on nodejs. We can't append logs to static array ...

Fixed memory leak.

---

lib/spec-converter.js

Sorry for the duplicate PR against master

Update spec-converter.js to take into account obj.basePath

---

browser/swagger-client.js

Reverts swagger-api/swagger-js#370

Revert "parseBody handle whitespace in responses"

---

browser/swagger-client.js

Reverts swagger-api/swagger-js#454

Revert "Don't warn when produces is "*/*"."

---

test/spec/v1/api-docs.json
test/spec/v2/petstore.js
test/spec/v2/petstore.json
test/spec/v2/petstore.yaml

fixes https://github.com/swagger-api/swagger-js/issues/462
Changed the email addresses in the spec file
@webron before we merge this, I want to know whether we are keeping the oauth urls.
https://github.com/swagger-api/swagger-js/blob/master/test/spec/v2/petstore.json#L807

change email address in spec files to apiteam@swagger.io

---

CONTRIBUTING.md

(Same as https://github.com/swagger-api/swagger-ui/pull/1408)

Improve the language in CONTRIBUTING.md

---

lib/client.js

Reverts swagger-api/swagger-js#539

Revert "Ability to choose scheme on client init.."

---

lib/client.js
lib/types/operation.js
test/compat/macros.js
test/compat/operation.js

fix macro support

---

lib/resolver.js
test/resolver.js

Removed redundant HTTP calls when resolving locally defined `$ref`s.

---

lib/types/operation.js

The patch was apply directly in https://github.com/swagger-api/swagger-ui/pull/1650
Closes https://github.com/swagger-api/swagger-ui/issues/1651

Allow x-www-form-urlencoded and formData

---

lib/resolver.js
test/resolver.js
test/spec/v2/absoluteRef.json
test/spec/v2/error.json
test/spec/v2/test.json

addresses https://github.com/swagger-api/swagger-ui/issues/1636

updated resolver and tests for #587

---

README.md

```js
var client = require('swagger-client');
var swagger = new client({
url: 'http://petstore.swagger.io/v2/swagger.json',
success: function() {
swagger.pet.getPetById({petId:7}, function(success){
console.log('succeeded and returned this object: + success.obj);
},
function(error) {
console.log('failed with the following: ' + error.statusText);
});
}
});
```
```js
var client = require('swagger-client');
var swagger = new client({
url: 'http://petstore.swagger.io/v2/swagger.json',
success: function() {
swagger.pet.getPetById({petId:7}, function(success){
console.log('succeeded and returned this object: ' + success.obj);
},
function(error) {
console.log('failed with the following: ' + error.statusText);
});
}
});
```

Fix README.md sample code

---

lib/client.js

Updated scheme resolution to use the incoming url even if schemes are defined

Https resolution based on url

---

lib/types/model.js

removed log statements, moved to comments

---

lib/http.js
test/client.js

updated jquery check, test

---

lib/schema-markup.js

Fix issue with tooltips, as reported in #674. 
Also applies to swagger-api/swagger-ui#1836

Fix tooltips within objects

---

lib/client.js

Added 'host' to the reservedClientTags list

---

lib/spec-converter.js

added config for accept headers

---

README.md

You're using `superagent` now, not `shred`, right?

Corrected request library in README

---

README.md

I tried this example as it's written and it didn't work.  I made the changes I put in this PR and it didn't work.  I'm pretty sure this is a mistake unless there's something about this package and about javascript that I'm completely unaware of

Fix error in Authorization example

---

test/models.js

Added allOf test

---

README.md

I had troubles with samples for auth (I have not the fastest mind :snail: ...), so I would like to make documentation a little bit more clearer with this PR
-----
Thanks this SO answer: http://stackoverflow.com/a/32149574/1115187

Make docs about auth more understandable

---

lib/types/operation.js
test/browser/http.js
test/client.js
test/help.js

Fixeds #917 by masking passwords when calling `asCurl`

added maskPassword function

---

lib/types/operation.js
test/help.js

don't mask www-form-url-encoded passwords in body

---

lib/client.js

A variable window.location is undefined on React Native.

check whether window.location is defined to work on React Native

---

test/client.js

added test

---

test/client.js
test/mock.js

added tests for promise behavior

---

test/durability.js

removed console logs

---

src/http.js
src/resolver.js
src/specmap/lib/refs.js
test/http.js

Allow loadSpec option to override content type

---

src/execute.js
test/execute.js

Reverts swagger-api/swagger-js#970

Revert "HTTP: Send cookies 'same-origin'"

---

src/index.js
src/resolver.js
test/http.js
test/index.js

Reverts swagger-api/swagger-js#987

Revert "Allow mocking http function"

---

src/execute.js
test/execute.js

Fixes https://github.com/swagger-api/swagger-ui/issues/2815

Catch baseUrls that have trailing slashes in them

---

src/index.js
test/client.js
test/data/pathless.json
test/data/pathless.yaml
test/data/petstore.json

Added tests

---

test/client.js

This enables the test which will ensure that missing host, schemes are added based on request url of the spec

enable test for partial fix of #1000

---

test/resolver.js

for swagger-api/swagger-ui#3012

Add regression test to resolver

---

src/http.js
test/http.js

The [HTTP Client section of README.md](https://github.com/swagger-api/swagger-js/blob/v3.0.8/README.md#http-client) documents the Error object as having a `.response` property with "response or null".  It does not appear that this feature has been implemented, as demonstrated by the following code:
```js
'use strict'
const assert = require('assert')
const http = require('http')
const SwaggerClient = require('swagger-client')
const TEST_HOST = 'localhost'
const TEST_ID = 123
const TEST_PORT = 8888
http
.createServer((req, res) => {
assert.strictEqual(req.url, '/data')
res.writeHead(400, {'Content-Type': 'application/json'})
res.end(JSON.stringify({message: 'Server-defined error message'}))
})
.listen(TEST_PORT, TEST_HOST, () => {
// Usage as documented in HTTP Client section of README.md …
```

Include .response property on Errors as documented

---

src/execute.js
test/execute.js

Reverts swagger-api/swagger-js#1041
Due to https://github.com/swagger-api/swagger-js/issues/1040#issuecomment-300413286

Revert "Do not depend the Authorization header on the token type."

---

src/execute.js
src/helpers.js
src/index.js
src/interfaces.js
test/client.js
test/helpers.js
test/interfaces.js

⚠️ **Work in progress, don't merge - but please do review code.**
Fixes #1003, paves the way for https://github.com/swagger-api/swagger-ui/issues/2884.
Changelog forthcoming.

Rewire operationIds

---

src/execute.js

Stringify array in body

---

src/http.js
test/http.js

Fixes https://github.com/swagger-api/swagger-ui/issues/3101

Avoid encoding form data value

---

test/http.js

just a typo from a previous PR

Remove instance of .only in a test

---

src/resolver.js
src/specmap/index.js
src/specmap/lib/parameters.js
src/specmap/lib/properties.js
test/specmap/parameters.js
test/specmap/properties.js

related to https://github.com/swagger-api/swagger-ui/issues/3067

parameterMacro, modelPropertyMacro

---

src/helpers.js
test/helpers.js

Fixes https://github.com/swagger-api/swagger-ui/issues/3203.

Fix __originalOperationId bug and improve test cases

---

src/specmap/index.js

Replace [].find with lodash/find for ie11

---

src/execute.js
test/execute.js

Include `0` values in query strings

---

.travis.yml

MOAR speed!
Before: 3.5 minutes
After: 1.3 minutes
- Removed unnecessary build toolchain and g++ Ubuntu packages
- Moved to Travis' new docker infrastructure (`sudo :false`)
- Began caching `node_modules`, and keeping dependencies fresh via `npm update`

Travis performance

---

README.md

Add security contact

---

src/http.js
src/specmap/lib/refs.js
test/http.js
test/specmap/index.js

Fixes case mentioned in https://github.com/swagger-api/swagger-ui/issues/3788#issuecomment-349489619.
cc: @banders

 Mend ability to serialize primitives in request body object values

---

src/http.js

FIX: operations with XSLS file
Fix issue about download XSLS files 
Root of issue that content type of XSLX files is 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' According actual version of application it will be interpreted as text, but should be as blob, to fix it we need to fix RegExp pattern used to detect text files

Fix: XSLX file operations

---

README.md

doc: fix browser example

---

test/client.js

Adds test case for #1288 - no source changes!

tests: add passing case for document fetch error catching

---

src/helpers.js
test/bugs/ui-4466.js

cc https://github.com/swagger-api/swagger-ui/issues/4466 & https://github.com/swagger-api/swagger-ui/issues/4467

fix: edge case where invalid parameter locks up normalizer

---

src/execute/oas3/build-request.js
test/oas3/execute/main.js

Supporting changes for https://github.com/swagger-api/swagger-ui/pull/4592

OAS3 binary media type support

---

release/.release-it.json
release/get-changelog.sh

Automated release touchups

---

release/.release-it.json

Revert "build(automated-release): enable Git push from `release-it`"

---

test/resolver.js

Adds a failing test to support https://github.com/swagger-api/swagger-js/issues/1330

add failing test for edge case resolver issue. allOf + items + $refs

---

README.md

improve: README.md

---

release/.release-it.json

Reverts swagger-api/swagger-js#1402

revert: "housekeeping(release): update lint command"

---

LICENSE

housekeeping: happy new year!

---

src/http.js

https://github.com/swagger-api/swagger-js/issues/1418

Use `JSON.parse` method for all types and encodings of `json`

---

package-lock.json
src/execute/oas3/parameter-builders.js
src/execute/swagger2/parameter-builders.js
test/execute/main.js
test/oas3/execute/main.js

Fixes https://github.com/swagger-api/swagger-ui/issues/5187.

fix: support path parameter inclusion when used twice in a path

---

src/constants.js
src/resolver.js
src/specmap/lib/refs.js

for https://github.com/swagger-api/swagger-js/issues/1475

improvement: factor out Accept value for document fetches

---

LICENSE

2️⃣0️⃣2️⃣0️⃣

---

docs/HTTP_CLIENT.md

Ref #729 #1228 #1409
Increase documentation coverage for HTTP Client
Multiple requests for better documentation
All the code examples used inside the docs have been tested.

docs(HTTP_Client): increase documentation coverage

---

docs/TRY_IT_OUT_EXECUTOR.md

Increase documentation coverage for TryItOut functionality
Multiple requests for better documentation
All the code examples used inside the docs have been tested.

docs(TryItOut): increse documentation coverage

---

docs/OPENAPI_DEFINITION_RESOLVER.md
docs/SWAGGER_SPECIFICATION_RESOLVER.md

Ref #729 #1228 #1409
Adds full documentation for Swagger specification resolver
Multiple requests for better documentation
All the code examples used inside the docs have been tested.

docs: add full documentation for swagger spec resolver

---

README.md
docs/SUMMARY.md
docs/development/scripts.md
docs/development/setting-up.md
docs/usage/api.md
docs/usage/http-client.md
docs/usage/installation.md
docs/usage/tags-interface.md

This PR consolidates Swagger Client documentation to reflect the same principles used in swagger-ui
Make documentation better
Every code example have been tested.

Documentation consolidation

---

docs/usage/openapi-definition-resolver.md

docs(resolver): mention  instance method

---

docs/usage/openapi-definition-resolver.md

docs(resolver): fix  option default value and description

---

docs/usage/try-it-out-executor.md

docs(try-it-out): add array parameter example

---

docs/usage/try-it-out-executor.md

docs(try-it-out): document interceptor options

---

docs/usage/try-it-out-executor.md

When set to true, Attaches a  header to a  even when no payload was provided for the .
- [] I have added tests to cover my changes.

docs(try-it-out): add docs for attachContentTypeForEmptyPayload option

---

docs/usage/tags-interface.md

docs(tags-interface): add file uploads example

---

docs/usage/http-client.md

docs(http-client): document possible upload progress

---

test/client.js

Ref #1511
Tests failing depending on node version
By running tests

test(client): fix test for requesting https over http

---

docs/usage/tags-interface.md

docs(tags-interface): document usage of security

---

docs/usage/tags-interface.md
src/execute/index.js

docs(tags-interface): add authorizations example

---

docs/usage/http-client.md
docs/usage/openapi-definition-resolver.md

Add authorization example for OAS resolver
Frequent support questions around this topic

docs(resolver): add authorization example

---

docs/usage/openapi-definition-resolver.md

Make the documentation for definition resolver better
Question was asked about `$$ref` and the explanation in documentation was insufficient to understand what it really is.

docs(resolver): add better explanation + examples for meta patches

---

test/execute/main.js

test(execute): fix rogue test

---

README.md
docs/development/setting-up.md

Ref #1532, #1534
Setting clear expectations about runtime and build support.

docs: add info about dev and runtime requirements

---

docs/usage/http-client.md

docs(http-client): access Request via responseInterceptor

---

test/data/sample-multipart-oas3.js

Fix the OAS3 http-multipart test sample definition for `file`
> OAS3 does not have type: file, it uses type: string + format: binary.

housekeeping: sample OAS3 schema definition compliance

---

src/http.js

fix(build-artifacts): fix corrupted build artifacts

---

package-lock.json
package.json
src/specmap/lib/index.js

Along with that update fast-json-patch to v2.2.1
Refs #1464

refactor(fast-json-patch): change all imports to star notation

---

.github/workflows/nodejs.yml

ci(GA): use github actions as CI

---

.dependabot/config.yml

chore(deps): add dependabot config

---

.github/workflows/nodejs.yml

ci(GA): eliminate unsuporrted node versions

---

.github/workflows/nodejs.yml
package-lock.json
package.json

We're making security audits part of CI pipeline. This check will make sure we're not using unsecure code in our build artifacts.

ci(GA): add security audit checks on deps

---

config/webpack/node.config.babel.js
package.json

fix(build): include sourcemap along with build artifact in npm distro

---

docs/GRAVEYARD.md
docs/MIGRATION_2_X.md

Those 2 files served as a temporary pointer for new documentation files places inside `docs/` directory. We kept them long enough and now we're removing them in favor of new files placed inside `docs/` directory.

docs: remove obsolete file pointers

---

.github/workflows/nodejs.yml
scripts/npm-audit.js

ci(npm-audit): make npm audit output on failure only

---

docs/usage/openapi-definition-resolver.md
src/index.js

fix(resolver): support legacy fetch override as an alias of http

---

docs/development/setting-up.md

docs(setting-up): add section about linking swagger-js and swagger-ui

---

.npmrc
package-lock.json
package.json

There are two separate commits. One fixing lodash security advisory, other one
allowing less strict ranges of production dependencies to be installed.

Security related changes

---

package-lock.json
package.json

Closes #1641
Closes #1642
Closes #1643
Closes #1644
Closes #1645

chore(deps): update dependencies to latest versions

---

babel.config.js
package-lock.json
package.json
test/build-artifacts/es.js

Refs #1715
Updates our polyfills from unmaintained core-js@2 to actively maintained core-js@3
core-js@2 is no longer maintained

feat(build): use core-js@3

---

docs/usage/http-client.md

Refs #1254
Timeouts and request cancellation are requirements that are frequently needed. This PR
add documentation about how to achieve both.
All examples have been manually tested.

docs(http-client): document request cancellation via AbortSignal

---

docs/development/scripts.md

docs(scripts): fix typo

---

docs/development/setting-up.md
package.json

Remove engines field from package.json #1684 
Remove engine field from package.json
it solves nvm version warnings
#1684 
Fixes #1684
checked manually before PR. project was building without failures

Remove engines field from package.json #1684

---

docs/usage/installation.md

Amend Installation documentation
Removed `/browser` directory mention from documentation
#1740

fix: Installation documentation #1740

---

package-lock.json
package.json

chore(deps-dev): bump webpack-cli from 4.0.0 to 4.1.0

---

.github/workflows/nodejs.yml

ci: automerge dependabot PRs that passes CI

---

.github/workflows/nodejs.yml

ci(GA): use swagger-bot token

---

.github/workflows/nodejs.yml

ci(merge-me): run only on dependabot actor

---

package-lock.json
package.json
src/execute/index.js

chore(dev-deps): update prettier to v2.2.0

---

package-lock.json

chore(security): update yargs-parser to v15.0.1

---

package-lock.json

chore(security): update ajv to v6.12.3

---

package-lock.json
package.json
src/execute/index.js
src/execute/oas3/style-serializer.js
src/helpers.js
src/interfaces.js
src/internal/form-data-monkey-patch.js
src/resolver.js
src/specmap/index.js
src/specmap/lib/all-of.js
src/specmap/lib/index.js
src/specmap/lib/refs.js
test/client.js
test/helpers.js
test/http-multipart.js
test/http.js
test/index.js
test/specmap/all-of.js
test/specmap/complex.js
test/specmap/index.js
test/specmap/refs.js

style(prettier): update eslint-config-prettier to v7.0.0

---

package-lock.json
src/resolver.js

docs(resolver): remove reference to non-existing specmap repo

---

config/webpack/browser.config.babel.js
package-lock.json
package.json

chore(deps-dev): bump terser-webpack-plugin from 4.2.3 to 5.0.3

---

package.json

fix(husky): remove postinstall script

---

.github/workflows/nodejs.yml

This will speed up the workflows significantly.
Closes #2022

ci(GA): utilize caching of node_modules

---

.releaserc

ci(release): add base semantic-release config

---

.github/workflows/release.yml
.releaserc

ci(release): project current semver in repository

---

package.json

chore(package): expose prepublishOnly script

---

package-lock.json
package.json
test/specmap/all-of.js
test/specmap/index.js

chore(deps-dev): bump jest from 26.6.3 to 27.0.1

---

src/http.js

Replaces https://github.com/swagger-api/swagger-js/pull/2093
We were unable to rebase the PR as author did not allow it whole creating the PR.

fix: add failback error message in case if HTTP/2 in Chrome

---

package.json

fix(package): add additional mappings for browser field

---

src/specmap/lib/refs.js

build(fetch): unify how we use cross-fetch

---

package-lock.json

chore(deps-dev): fix security vulnerabilities

---

package-lock.json
package.json
test/execute/main.js

chore(deps): bump form-data-encoder to v1.4.3

---

.eslintrc
package-lock.json
package.json
src/http/fold-formdata-to-request.node.js
src/http/index.js
test/http/http-multipart.js
test/http/index.js

chore(deps): bump formdata-node from 3.7.0 to 4.0.0

---

.npmrc
package.json

This fixes security vulnerability in older version of lodash.
Vuln URL: https://snyk.io/vuln/SNYK-JS-LODASH-1018905
Refs https://github.com/swagger-api/swagger-ui/issues/7473

fix(security): depend on min version of lodash >= 4.17.21

---

README.md

chore(build-status): replace Jenkins badge with GitHub Actions

---

README.md

chore(build-status): link to Actions tab

---

.github/workflows/dependabot-merge.yml

ci(dependabot): sqash and merge instead of merge commit

---

src/helpers.js
src/http/index.js
src/index.js
src/specmap/helpers.js
src/specmap/index.js

got rid of more lodash stuff
part of #2187 
- npm run test
- npm run lint

removed more lodash stuff

---

src/http/index.js

To support both uint8 and buffer (and any other view)
... buffer is a node specific thing...
npm run lint && npm run test
closes #2243

Replace isBuffer with isView

---

src/specmap/lib/all-of.js

replace lodash/isEmpty with vanilla

---

src/helpers.js

Regression was introduced in 067229e.
Refs https://github.com/swagger-api/swagger-ui/issues/7771

fix(normalizeSwagger): fix regression in swagger normalization

---

package-lock.json
package.json
test/specmap/data/cyclic/external/1.js
test/specmap/data/cyclic/external/10.js
test/specmap/data/cyclic/external/2.js
test/specmap/data/cyclic/external/20.js
test/specmap/data/cyclic/external/21.js
test/specmap/data/cyclic/external/30.js
test/specmap/data/cyclic/external/31.js
test/specmap/data/cyclic/external/32.js
test/specmap/data/cyclic/external/40.js

Refs https://github.com/advisories/GHSA-r683-j2x4-v87g

fix(security): update cross-fetch to >=3.1.5

---

package-lock.json
package.json

chore(deps-dev): update node-fetch dev dep to v2.6.7

---

.github/workflows/nodejs.yml

ci: do not lint comming msg on master

---

package-lock.json
package.json
src/http/index.js
src/specmap/lib/refs.js

chore(deps-dev): bump eslint from 8.15.0 to 8.21.0

---

docs/usage/http-client.md

Fix typo(http-client.md)

---

.github/workflows/dependabot-merge.yml

Refs https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/166

ci(dependabot-merge): replace non-functioning action

---

.eslintrc
package-lock.json
package.json
src/helpers/apidom/openapi-3-1/parsers/json/index.js

feat(resolve): add ApiDOM JSON parser

---

.github/workflows/release.yml
.releaserc

chore(release): configure CD pipeline for 3.19.x-alpha channel

---

src/index.js

feat: expose ApiDOM components as public API

---

README.md
docs/development/scripts.md
docs/development/setting-up.md

docs: document local dev setup

---

test/execute/openapi-3-1.js

test: add OpenAPI 3.1.0 test for HTTP Client for OAS operations

---

test/execute/openapi-3-1.js
test/interfaces.js

test: add OpenAPI 3.1 test for Tags Interfaces

---

.github/workflows/release.yml
.releaserc

ci(release): configure beta release channel

---

.github/workflows/release.yml

ci(release): enable beta release channel

---

package-lock.json
package.json

feat(build): limit the size on npm package as much as possible

---

package-lock.json
package.json
src/resolver/apidom/reference/parse/parsers/json/index.js
src/resolver/apidom/reference/parse/parsers/openapi-json-3-1/index.js
src/resolver/apidom/reference/parse/parsers/openapi-yaml-3-1/index.js
src/resolver/apidom/reference/parse/parsers/yaml-1-2/index.js
src/resolver/apidom/reference/resolve/resolvers/http-swagger-client/index.js

Refs https://github.com/swagger-api/apidom/issues/2561

fix(resolver): use native error cause syntax with ApiDOM errors

---

.github/workflows/nodejs.yml
.github/workflows/release.yml
.npmrc
docs/development/setting-up.md
docs/usage/installation.md
package-lock.json
package.json

feat(deps): use ApiDOM npmjs.com npm packages

---

package-lock.json
package.json
test/specmap/complex.js
test/specmap/refs.js

chore(deps-dev): bump glob from 8.1.0 to 9.2.1

---

src/helpers/openapi-predicates.js

fix: use forward compatible OpenAPI version detection

---

src/resolver/strategies/openapi-3-1-apidom/resolve.js

Refs https://github.com/swagger-api/swagger-ui/issues/8606

perf(resolver): utilize cache for OpenAPI 3.1

---

src/specmap/helpers.js

fix(specmap): add backward compat relative URL Reference resolution

---

src/constants.js
src/execute/index.js
src/resolver/strategies/openapi-3-1-apidom/resolve.js
src/specmap/helpers.js
test/resolver/strategies/openapi-3-1-apidom/__snapshots__/index.js.snap
test/subtree-resolver/strategies/openapi-3-1-apidom/__snapshots__/index.js.snap

fix(specmap): provide multi platform backward compat

---

src/resolver/utils/options.js

fix(resolver): allow to provide relative URI Reference in browser env

---

package-lock.json
package.json
src/execute/index.js
src/http/index.js

chore(deps-dev): bump prettier from 3.0.3 to 3.1.1

---

docs/usage/installation.md
package-lock.json
package.json

feat: integrate ApiDOM@0.90.0

---

src/specmap/index.js
test/specmap/complex.js

Refs #3385, https://github.com/swagger-api/swagger-ui/issues/9645

fix(specmap): change traversal limit logic

---

src/execute/swagger2/parameter-builders.js
test/execute/main.js

fix(execute): add falsy formData values to requests

---

src/execute/swagger2/parameter-builders.js
test/execute/main.js

fix(execute): align form data builder with query builder behaviour

---

.github/dependabot.yml
package-lock.json
package.json

Refs https://github.com/swagger-api/swagger-ui/issues/9857

chore(deps): pin traverse to v0.6.8

---

.github/dependabot.yml

Refs https://github.com/swagger-api/swagger-js/pull/3483

ci(dependabot): ignore semver-major updates for unidic@5

---

src/execute/index.js

fix(security): remedy polynomial regular expression without limiting length to 29 chars

---

.github/workflows/codeql.yml

The basic setup without workflow file doesn't work 100% and sometimes skips PR.s

ci: use advanced CodeQL analysis

---

src/resolver/strategies/openapi-3-1-apidom/normalize.js
test/resolver/strategies/openapi-3-1-apidom/__snapshots__/index.js.snap
test/resolver/strategies/openapi-3-1-apidom/normalize/__snapshots__/index.js.snap
test/subtree-resolver/strategies/openapi-3-1-apidom/__snapshots__/index.js.snap

fix(resolver): disable Server Objects normalization for OpenAPI 3.1.0

---

.github/dependabot.yml
package-lock.json
package.json
src/resolver/specmap/helpers.js
test/resolver/specmap/index.js

chore(deps): replace traverse with neotraverse

---

src/http/serializers/request/index.js

refactor(http): use native URLSearchParams where possible

---

README.md

Readme fixed around scarf description
Just spotted a inconsistency that seems to be a typo.
Just spotted a inconsistency that seems to be a typo.
Reviewed rendered readme

fix: README md typo around scafe/scarf

---

package-lock.json
package.json

Refs https://github.com/scarf-sh/scarf-js/issues/72

chore(deps): update Scarf.js to v1.4.0

---

package-lock.json
package.json

Refs https://github.com/OAI/OpenAPI-Specification/pull/4279

fix(execute): apply fix for faulty OpenAPI Path Templating ABNF

---

src/resolver/specmap/index.js
test/subtree-resolver/strategies/openapi-2--3-0.js

Refs https://github.com/swagger-api/swagger-ui/issues/10096

fix(specmap): fix resolver being affected by the order of schemas
